"""Site health check workflow — proactive frontend monitoring via vision analysis.

Runs on a Hatchet cron schedule (every 4 hours). For each project with a known
frontend port, reads page paths from .index.yaml (generated by the SummitFlow
explorer), screenshots each page via subprocess, then sends all screenshots to a
vision model for analysis. If issues are found, wakes the persona for triage.
"""

from __future__ import annotations

import asyncio
import base64
import contextlib
import json
import logging
import os
import re
from pathlib import Path
from typing import Any

import yaml
from hatchet_sdk import ConcurrencyExpression, ConcurrencyLimitStrategy, Context
from pydantic import BaseModel

from app.hatchet_app import hatchet

logger = logging.getLogger(__name__)

# Project → frontend port mapping (from service port map)
FRONTEND_PORTS: dict[str, int] = {
    "summitflow": 3001,
    "agent-hub": 3003,
    "portfolio-ai": 3000,
    "terminal": 3002,
    "monkey-fight": 4001,
}

MAX_PAGES_PER_PROJECT = 5
CHECK_TIMEOUT_PER_PROJECT = 180  # seconds (increased for multi-page)


class HealthCheckResult(BaseModel):
    status: str
    projects_checked: int = 0
    projects_with_issues: int = 0
    project_findings: dict[str, str] = {}
    error: str | None = None


async def _run_cmd(*args: str, timeout: int = 30) -> str:
    """Run a subprocess command and return stdout. Raises on non-zero exit."""
    proc = await asyncio.create_subprocess_exec(
        *args,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(
            f"Command {args} failed (exit {proc.returncode}): "
            f"{stderr.decode().strip()}"
        )
    return stdout.decode().strip()


def _get_page_paths(project_id: str) -> list[str]:
    """Read page paths from project's .index.yaml, filtering dynamic routes.

    Falls back to ["/"] if the file doesn't exist or can't be parsed.
    The base directory for projects is read from the PROJECTS_BASE_PATH
    environment variable, defaulting to the user's home directory.
    """
    base_path = Path(os.environ.get("PROJECTS_BASE_PATH", str(Path.home())))
    index_path = base_path / project_id / ".index.yaml"
    if not index_path.exists():
        logger.warning(
            "Index file not found for project %s at %s; defaulting to '/'",
            project_id,
            index_path,
        )
        return ["/"]

    try:
        data = yaml.safe_load(index_path.read_text())
    except Exception:
        logger.warning("Failed to parse %s, defaulting to '/'", index_path, exc_info=True)
        return ["/"]

    paths = []
    for entry in data.get("pages", []):
        # Format: "path (name)" or just "path"
        path = entry.split(" (")[0].strip()
        # Skip dynamic routes (containing :param segments)
        if ":" not in path:
            paths.append(path)

    return paths[:MAX_PAGES_PER_PROJECT] if paths else ["/"]


async def _capture_page(
    url: str, page_path: str, is_first: bool
) -> dict[str, str]:
    """Navigate to a page, screenshot, and collect console data.

    Returns dict with keys: path, screenshot_b64, errors, console.
    The browser must already be open for the first page.
    """
    page_url = url.rstrip("/") + page_path

    # Navigate (first page is already loaded by the caller)
    if not is_first:
        # Clear console/errors from previous page
        with contextlib.suppress(Exception):
            await _run_cmd("agent-browser", "errors", "--clear")
        with contextlib.suppress(Exception):
            await _run_cmd("agent-browser", "console", "--clear")

        await _run_cmd("agent-browser", "open", page_url)
        await _run_cmd("agent-browser", "wait", "--load", "networkidle", timeout=30)

    # Screenshot
    screenshot_b64 = ""
    screenshot_raw = await _run_cmd("agent-browser", "screenshot", "--json")
    try:
        screenshot_data = json.loads(screenshot_raw)
        screenshot_path = screenshot_data.get("data", {}).get("path", "")
    except (json.JSONDecodeError, AttributeError):
        screenshot_path = ""

    if screenshot_path:
        with contextlib.suppress(OSError):
            screenshot_b64 = base64.b64encode(Path(screenshot_path).read_bytes()).decode()

    # Console errors
    try:
        errors = await _run_cmd("agent-browser", "errors", "--json")
    except Exception:
        errors = "No errors captured"

    # Console output
    try:
        console = await _run_cmd("agent-browser", "console", "--json")
    except Exception:
        console = "No console output captured"

    return {
        "path": page_path,
        "screenshot_b64": screenshot_b64,
        "errors": errors,
        "console": console,
    }


async def _capture_page_safe(
    project_id: str, url: str, page_path: str, is_first: bool
) -> dict[str, str] | None:
    """Call _capture_page and return None on any failure."""
    try:
        return await _capture_page(url, page_path, is_first=is_first)
    except Exception as e:
        logger.warning("Failed to capture %s%s: %s", project_id, page_path, e)
        return None


async def run_browser_captures(
    project_id: str, url: str, page_paths: list[str]
) -> list[dict[str, str]]:
    """Phase 1: Open a browser session and capture screenshots for each page path.

    Opens the first page, iterates over all paths collecting screenshots and
    console data, then closes the browser. Returns a list of capture dicts.
    """
    try:
        await _run_cmd("agent-browser", "open", url + page_paths[0])
        await _run_cmd("agent-browser", "wait", "--load", "networkidle", timeout=60)
    except Exception as e:
        with contextlib.suppress(Exception):
            await _run_cmd("agent-browser", "close")
        raise RuntimeError(f"Failed to load {url}: {e}") from e

    captures: list[dict[str, str]] = []
    try:
        for i, page_path in enumerate(page_paths):
            capture = await _capture_page_safe(project_id, url, page_path, is_first=(i == 0))
            if capture and capture["screenshot_b64"]:
                captures.append(capture)
    finally:
        with contextlib.suppress(Exception):
            await _run_cmd("agent-browser", "close")

    return captures


def build_user_content(
    captures: list[dict[str, str]], project_id: str, url: str
) -> list[dict[str, Any]]:
    """Build the vision-model content block list from a set of page captures.

    Interleaves image blocks and text context blocks for each captured page,
    then appends a final analysis instruction.
    """
    user_content: list[dict[str, Any]] = []
    for capture in captures:
        user_content.append(
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": capture["screenshot_b64"],
                },
            }
        )
        user_content.append(
            {
                "type": "text",
                "text": (
                    f"Page: {capture['path']}\n"
                    f"Console errors: {capture['errors'][:800]}\n"
                    f"Console output: {capture['console'][:800]}"
                ),
            }
        )

    user_content.append(
        {
            "type": "text",
            "text": (
                f"\nAnalyze these {len(captures)} page(s) of the {project_id} "
                f"frontend at {url}. Report each finding with severity "
                "(critical/warning/info) and which page it affects. "
                "If everything looks healthy, say 'No issues found.'"
            ),
        }
    )
    return user_content


async def analyze_captures(
    project_id: str,
    user_content: list[dict[str, Any]],
) -> tuple[str, bool]:
    """Phase 2: Send captured screenshots to a vision model and return findings.

    Tries the primary model then each fallback in order. Returns
    (findings_text, has_issues). If all models fail, returns has_issues=True
    so the failure triggers investigation rather than being silently suppressed.
    """
    from app.adapters.registry import get_provider_for_model
    from app.api.complete.core import complete_internal
    from app.db import async_session
    from app.services.agent_routing_utils import resolve_agent

    try:
        async with async_session() as db:
            resolved = await resolve_agent("site-checker", db)

            models = [resolved.model]
            models.extend(resolved.agent.fallback_models or [])

            system_prompt = (
                resolved.agent.system_prompt
                or "Analyze the screenshot and report issues."
            )
            messages: list[dict[str, Any]] = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ]

            last_error: Exception | None = None
            for model in models:
                try:
                    provider = get_provider_for_model(model)
                    result = await complete_internal(
                        messages=messages,
                        model=model,
                        provider=provider,
                        temperature=resolved.agent.temperature,
                        project_id=project_id,
                        db=db,
                        agent_slug="site-checker",
                        request_source="site_health_check",
                        use_memory=False,
                        max_turns=1,
                        execute_tools=False,
                        timeout_seconds=60.0,
                    )
                    content = result.content or ""
                    has_issues = bool(
                        re.search(
                            r"^(critical|warning|error|broken|failed to load)\b",
                            content,
                            re.IGNORECASE | re.MULTILINE,
                        )
                    )
                    return content[:4000], has_issues
                except Exception as e:
                    last_error = e
                    logger.warning(
                        "Model %s failed for %s: %s", model, project_id, e
                    )
                    continue

            return f"All models failed for {project_id}: {last_error}", True

    except Exception as e:
        logger.warning("Site check analysis failed for %s: %s", project_id, e)
        return f"Error analyzing {project_id}: {e}", True


async def _check_project(project_id: str, port: int) -> tuple[str, bool]:
    """Run browser subprocess commands + vision analysis against a project frontend.

    Delegates to three helpers:
      - run_browser_captures(): Phase 1 browser navigation and screenshot loop.
      - build_user_content(): assembles content blocks for the vision model.
      - analyze_captures(): Phase 2 vision-model call with model fallback.

    Returns (findings_text, has_issues).
    """
    url = f"http://localhost:{port}"
    page_paths = _get_page_paths(project_id)

    try:
        captures = await run_browser_captures(project_id, url, page_paths)
    except RuntimeError as e:
        return str(e), True

    if not captures:
        return f"No screenshots captured for {project_id}", True

    user_content = build_user_content(captures, project_id, url)
    return await analyze_captures(project_id, user_content)


async def _wake_persona_with_site_findings(result: HealthCheckResult) -> None:
    """Wake persona agent with site health findings for triage."""
    from app.db import async_session
    from app.services.agent_routing import get_provider_for_model
    from app.services.agent_service import get_agent_service
    from app.workflows.persona_wake import WakeInput, agent_wake_task

    sections = []
    for project, findings in result.project_findings.items():
        if findings and not findings.startswith("Error"):
            sections.append(f"## {project}\n{findings[:2000]}")

    if not sections:
        return

    findings_text = "\n\n".join(sections)
    prompt = (
        f"Site health check completed. "
        f"{result.projects_with_issues} project(s) with issues "
        f"out of {result.projects_checked} checked.\n\n"
        f"Review the findings and take action:\n"
        f"- For critical issues: create tasks or dispatch the fixer agent\n"
        f"- For warnings: log them and monitor\n"
        f"- For info items: note in journal if patterns emerge\n\n"
        f"Findings:\n{findings_text}"
    )

    async with async_session() as db:
        agent_service = get_agent_service()
        agent = await agent_service.get_by_slug(db, "persona")
        if not agent:
            logger.warning("Persona agent not found, skipping wake for site health findings")
            return
        provider = get_provider_for_model(agent.primary_model_id)

    wake_input = WakeInput(
        agent_slug="persona",
        model=agent.primary_model_id,
        provider=provider,
        temperature=agent.temperature,
        prompt=prompt,
        project_id="agent-hub",
        event_type="site_health_check",
        thinking_level=agent.thinking_level,
    )
    agent_wake_task.run_no_wait(wake_input)
    logger.info("Persona woken with site health findings (%d issues)", result.projects_with_issues)


class SingleProjectCheckInput(BaseModel):
    project_id: str
    task_id: str | None = None


@hatchet.task(
    name="single-project-health-check",
    execution_timeout="300s",
    retries=0,
    input_validator=SingleProjectCheckInput,
)
async def single_project_health_check_task(
    input: SingleProjectCheckInput, ctx: Context
) -> dict[str, Any]:
    """On-demand site health check for a single project (post-merge)."""
    project_id = input.project_id
    port = FRONTEND_PORTS.get(project_id)
    if not port:
        return {"status": "skipped", "error": f"Unknown project: {project_id}"}

    # Poll for service readiness (up to 60s, 5s intervals)
    url = f"http://localhost:{port}"
    ready = False
    for _ in range(12):
        try:
            await _run_cmd("curl", "-sf", "-o", "/dev/null", url, timeout=5)
            ready = True
            break
        except Exception:
            await asyncio.sleep(5)

    if not ready:
        ctx.log(f"Service {project_id} not ready at {url} after 60s")
        return {"status": "error", "error": f"Service not ready: {url}"}

    ctx.log(f"Checking {project_id} at localhost:{port}")
    findings, has_issues = await _check_project(project_id, port)

    if has_issues:
        result = HealthCheckResult(
            status="issues_found",
            projects_checked=1,
            projects_with_issues=1,
            project_findings={project_id: findings},
        )
        try:
            await _wake_persona_with_site_findings(result)
            ctx.log(f"Persona woken for {project_id} site issues")
        except Exception as e:
            logger.warning("Failed to wake persona for %s: %s", project_id, e)

    return {
        "status": "issues_found" if has_issues else "healthy",
        "project_id": project_id,
        "task_id": input.task_id,
        "findings": findings[:2000],
    }


@hatchet.task(
    name="site-health-check",
    input_validator=BaseModel,
    on_crons=["30 14 * * 1-5", "0 7 * * *"],  # 2:30pm Mon-Fri + 7am daily
    execution_timeout="900s",  # 15 min total
    concurrency=ConcurrencyExpression(
        expression="'site_health_check'",
        max_runs=1,
        limit_strategy=ConcurrencyLimitStrategy.CANCEL_IN_PROGRESS,
    ),
)
async def site_health_check_task(input: BaseModel, ctx: Context) -> dict[str, Any]:
    """Scheduled site health check across all frontend projects."""
    try:
        project_findings: dict[str, str] = {}
        projects_with_issues = 0

        for project_id, port in FRONTEND_PORTS.items():
            ctx.log(f"Checking {project_id} at localhost:{port}")
            findings, has_issues = await _check_project(project_id, port)
            project_findings[project_id] = findings
            if has_issues:
                projects_with_issues += 1

        result = HealthCheckResult(
            status="success",
            projects_checked=len(FRONTEND_PORTS),
            projects_with_issues=projects_with_issues,
            project_findings=project_findings,
        )

        ctx.log(
            f"Site health: {result.projects_checked} checked, "
            f"{projects_with_issues} with issues"
        )

        if projects_with_issues > 0:
            try:
                await _wake_persona_with_site_findings(result)
                ctx.log("Persona woken for triage")
            except Exception as e:
                logger.warning("Failed to wake persona with site findings: %s", e)

        return result.model_dump()

    except Exception as e:
        logger.exception("Site health check failed")
        return HealthCheckResult(status="error", error=str(e)).model_dump()
