"""Tool definitions for the persona agent (personality, memory, scheduling, etc.).

This module re-exports all persona tool symbols from focused sub-modules:
- _persona_memory_tools: personality, user context, memory curation, onboarding
- _persona_schedule_tools: scheduling and subagent steering
- _persona_ops_tools: task orchestration, model config, agent performance
"""

from __future__ import annotations

from app.services.tools._notification_tools import SEND_PUSH_TOOL
from app.services.tools._persona_memory_tools import (
    MANAGE_MEMORY_TAGS_TOOL,
    MARK_MEMORY_IRRELEVANT_TOOL,
    MARK_MEMORY_RELEVANT_TOOL,
    READ_HEARTBEAT_INSTRUCTIONS_TOOL,
    READ_PERSONALITY_TOOL,
    READ_USER_CONTEXT_TOOL,
    REVIEW_MEMORY_SYSTEM_TOOL,
    SUBMIT_ONBOARDING_TOOL,
    WRITE_HEARTBEAT_INSTRUCTIONS_TOOL,
    WRITE_PERSONALITY_TOOL,
    WRITE_USER_CONTEXT_TOOL,
)
from app.services.tools._persona_ops_tools import (
    INSPECT_SESSION_TOOL,
    LOG_AGENT_PERFORMANCE_TOOL,
    MANAGE_BACKUPS_TOOL,
    MANAGE_FEEDBACK_TOOL,
    MANAGE_MODEL_CONFIG_TOOL,
    MANAGE_TASKS_TOOL,
    QUERY_SESSIONS_TOOL,
    REVIEW_AGENT_PERFORMANCE_TOOL,
    REVIEW_IMPROVEMENT_SIGNALS_TOOL,
    SEARCH_PERSONA_HISTORY_TOOL,
)
from app.services.tools._persona_schedule_tools import (
    CANCEL_CONSULTATION_TOOL,
    CANCEL_SCHEDULED_JOB_TOOL,
    DISPATCH_AGENT_TOOL,
    LIST_CONSULTATIONS_TOOL,
    LIST_SCHEDULED_JOBS_TOOL,
    SCHEDULE_JOB_TOOL,
    STEER_CONSULTATION_TOOL,
)
from app.services.tools.base import Tool

__all__ = [
    "CANCEL_CONSULTATION_TOOL",
    "CANCEL_SCHEDULED_JOB_TOOL",
    "DISPATCH_AGENT_TOOL",
    "INSPECT_SESSION_TOOL",
    "LIST_CONSULTATIONS_TOOL",
    "LIST_SCHEDULED_JOBS_TOOL",
    "LOG_AGENT_PERFORMANCE_TOOL",
    "MANAGE_BACKUPS_TOOL",
    "MANAGE_FEEDBACK_TOOL",
    "MANAGE_MEMORY_TAGS_TOOL",
    "MANAGE_MODEL_CONFIG_TOOL",
    "MANAGE_TASKS_TOOL",
    "MARK_MEMORY_IRRELEVANT_TOOL",
    "MARK_MEMORY_RELEVANT_TOOL",
    "PERSONA_EXTRA_TOOLS",
    "QUERY_SESSIONS_TOOL",
    "READ_HEARTBEAT_INSTRUCTIONS_TOOL",
    "READ_PERSONALITY_TOOL",
    "READ_USER_CONTEXT_TOOL",
    "REVIEW_AGENT_PERFORMANCE_TOOL",
    "REVIEW_IMPROVEMENT_SIGNALS_TOOL",
    "REVIEW_MEMORY_SYSTEM_TOOL",
    "SCHEDULE_JOB_TOOL",
    "SEARCH_PERSONA_HISTORY_TOOL",
    "SEND_PUSH_TOOL",
    "STEER_CONSULTATION_TOOL",
    "SUBMIT_ONBOARDING_TOOL",
    "WRITE_HEARTBEAT_INSTRUCTIONS_TOOL",
    "WRITE_PERSONALITY_TOOL",
    "WRITE_USER_CONTEXT_TOOL",
]

# Consolidated list of all persona-specific tools (excluding standard tools)
PERSONA_EXTRA_TOOLS: list[Tool] = [
    READ_PERSONALITY_TOOL,
    WRITE_PERSONALITY_TOOL,
    WRITE_USER_CONTEXT_TOOL,
    READ_USER_CONTEXT_TOOL,
    READ_HEARTBEAT_INSTRUCTIONS_TOOL,
    WRITE_HEARTBEAT_INSTRUCTIONS_TOOL,
    MANAGE_MEMORY_TAGS_TOOL,
    REVIEW_MEMORY_SYSTEM_TOOL,
    MARK_MEMORY_RELEVANT_TOOL,
    MARK_MEMORY_IRRELEVANT_TOOL,
    SUBMIT_ONBOARDING_TOOL,
    SCHEDULE_JOB_TOOL,
    LIST_SCHEDULED_JOBS_TOOL,
    CANCEL_SCHEDULED_JOB_TOOL,
    STEER_CONSULTATION_TOOL,
    LIST_CONSULTATIONS_TOOL,
    DISPATCH_AGENT_TOOL,
    CANCEL_CONSULTATION_TOOL,
    MANAGE_TASKS_TOOL,
    MANAGE_BACKUPS_TOOL,
    MANAGE_MODEL_CONFIG_TOOL,
    MANAGE_FEEDBACK_TOOL,
    LOG_AGENT_PERFORMANCE_TOOL,
    INSPECT_SESSION_TOOL,
    REVIEW_AGENT_PERFORMANCE_TOOL,
    REVIEW_IMPROVEMENT_SIGNALS_TOOL,
    QUERY_SESSIONS_TOOL,
    SEARCH_PERSONA_HISTORY_TOOL,
    SEND_PUSH_TOOL,
]
