reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - '!artifacts/**'
    - '!.dev-tools/**'
    - '!frontend/tests-results/**'
    - '!frontend/playwright-report/**'
    - '!**/*.snap'
    - '!**/__snapshots__/**'
chat:
  auto_reply: false
