project: agent-hub
generated_at: 2026-01-19 16:06 UTC
total_files: 773
folders:
  (root): 18 files - docs, tests - (claude, dev-tools, gitignore, json, md)
  .claude: 1 files - (json)
  .dev-tools: 12 files - tests - (txt)
  .qna-session: 1 files - (json)
  backend: 203 files - api, config, docs, models, services, storage, tests - (0, coverage,
    example, ini, json)
  docs: 6 files - api, docs - (md)
  examples: 6 files - docs - (md, py)
  frontend: 147 files - api, components, config, docs, models, storage, tests - (css,
    gitignore, js, json, md)
  monkey-fight: 2 files - tests - (py)
  packages: 324 files - api, components, config, docs, models, services, storage,
    tests - (example, github, gitignore, ini, ipynb)
  scripts: 14 files - services, tests - (py, service, sh)
  spec: 3 files - docs, tests - (json, md)
  tasks: 36 files - api, config, docs, models, tests - (json, md)
