"""Memory service module using PostgreSQL + pgvector."""

from .citation_parser import (
    Citation,
    CitationType,
    FeedbackParseResult,
    FeedbackTag,
    ParseResult,
    extract_feedback_tags,
    extract_uuid_prefixes,
    format_citation,
    format_guardrail_citation,
    format_mandate_citation,
    parse_citations,
    parse_feedback_tags,
    resolve_full_uuids,
)
from .context_injector import (
    inject_progressive_context,
    parse_memory_group_id,
)
from .episode_formatter import (
    EpisodeFormatter,
    get_episode_formatter,
)
from .episode_helpers import EpisodeOrigin
from .episode_validation import EpisodeValidationError
from .learning_extractor import extract_learnings
from .learning_models import (
    ExtractedLearning,
    ExtractionResult,
    ExtractLearningsRequest,
    LearningStatus,
    LearningType,
)
from .memory_client import get_memory_repository, init_memory_schema
from .memory_models import (
    EpisodeStatus,
    FormattedEpisode,
    InjectionTier,
    MemoryCategory,
    MemoryCategoryCount,
    MemoryContext,
    MemoryEpisode,
    MemoryListResult,
    MemoryScope,
    MemoryScopeCount,
    MemorySearchResult,
    MemorySource,
    MemoryStats,
)
from .memory_utils import build_group_id, resolve_uuid_prefix
from .promotion import (
    PromoteRequest,
    PromotionResult,
    ReinforcementResult,
    check_and_promote_duplicate,
    get_canonical_context,
    promote_learning,
)
from .service import MemoryService, get_memory_service
from .state import (
    MemoryState,
    cleanup_stale_states,
    create_state,
    delete_state,
    get_state,
)
from .tools import (
    get_session_context,
    record_discovery,
    record_gotcha,
    record_pattern,
)
from .tools_formatting import format_session_context_for_injection
from .tools_schemas import (
    RecordDiscoveryRequest,
    RecordGotchaRequest,
    RecordPatternRequest,
    RecordResponse,
    SessionContextResponse,
)
from .usage_flushers import init_usage_properties
from .usage_tracker import (
    get_usage_buffer,
    shutdown_usage_tracker,
    start_usage_tracker,
    track_harmful,
    track_helpful,
    track_loaded,
    track_loaded_batch,
    track_referenced,
    track_referenced_batch,
    track_success,
    track_success_batch,
)

__all__ = [
    "Citation",
    "CitationType",
    "EpisodeFormatter",
    "EpisodeOrigin",
    "EpisodeStatus",
    "EpisodeValidationError",
    "ExtractLearningsRequest",
    "ExtractedLearning",
    "ExtractionResult",
    "FeedbackParseResult",
    "FeedbackTag",
    "FormattedEpisode",
    "InjectionTier",
    "LearningStatus",
    "LearningType",
    "MemoryCategory",
    "MemoryCategoryCount",
    "MemoryContext",
    "MemoryEpisode",
    "MemoryListResult",
    "MemoryScope",
    "MemoryScopeCount",
    "MemorySearchResult",
    "MemoryService",
    "MemorySource",
    "MemoryState",
    "MemoryStats",
    "ParseResult",
    "PromoteRequest",
    "PromotionResult",
    "RecordDiscoveryRequest",
    "RecordGotchaRequest",
    "RecordPatternRequest",
    "RecordResponse",
    "ReinforcementResult",
    "SessionContextResponse",
    "build_group_id",
    "check_and_promote_duplicate",
    "cleanup_stale_states",
    "create_state",
    "delete_state",
    "extract_feedback_tags",
    "extract_learnings",
    "extract_uuid_prefixes",
    "format_citation",
    "format_guardrail_citation",
    "format_mandate_citation",
    "format_session_context_for_injection",
    "get_canonical_context",
    "get_episode_formatter",
    "get_memory_repository",
    "get_memory_service",
    "get_session_context",
    "get_state",
    "get_usage_buffer",
    "init_memory_schema",
    "init_usage_properties",
    "inject_progressive_context",
    "parse_citations",
    "parse_feedback_tags",
    "parse_memory_group_id",
    "promote_learning",
    "record_discovery",
    "record_gotcha",
    "record_pattern",
    "resolve_full_uuids",
    "resolve_uuid_prefix",
    "shutdown_usage_tracker",
    "start_usage_tracker",
    "track_harmful",
    "track_helpful",
    "track_loaded",
    "track_loaded_batch",
    "track_referenced",
    "track_referenced_batch",
    "track_success",
    "track_success_batch",
]
