"""Seed default agents into the database from seed_data.json.

Run with: python -m scripts.seed_agents

WARNING: This script is INSERT-ONLY by design. Do NOT add upsert/update logic.
The database is the source of truth for agent configuration (models, prompts,
temperatures, etc.). This script only bootstraps a fresh DB.

seed_data.json is AUTO-GENERATED by export_seeds.py. Never edit it by hand.
Use 'st prompt update' and the agent API for changes, then re-export.

To change agent config: use the UI, Alembic migrations, or direct DB updates.
Upsert logic was removed Feb 2026 after it silently overwrote manual model
assignments. See memory guardrail [G:8d98328d].
"""

import asyncio
import json
import logging
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings
from app.constants import resolve_model
from app.models import Agent
from app.models.prompt import AgentPrompt, Prompt
from app.services.owned_prompt_service import sync_agent_system_prompt

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)

SEED_FILE = Path(__file__).parent / "seed_agents_data" / "seed_data.json"


def _canonicalize_model_chain(models: list[str] | None) -> list[str]:
    seen: set[str] = set()
    canonical: list[str] = []
    for model in models or []:
        resolved = resolve_model(model)
        if not resolved or resolved in seen:
            continue
        seen.add(resolved)
        canonical.append(resolved)
    return canonical


def _load_seed_data() -> tuple[list[dict], set[str]]:
    """Load bootstrap agents and insert-time inactive defaults."""
    if not SEED_FILE.exists():
        logger.error("seed_data.json not found at %s", SEED_FILE)
        logger.error("Run 'python -m scripts.export_seeds' to generate it from the database.")
        raise FileNotFoundError(SEED_FILE)

    data = json.loads(SEED_FILE.read_text())

    if "_metadata" in data:
        meta = data["_metadata"]
        logger.info(
            "Loading seed data: %d agents (exported %s)",
            meta.get("agent_count", "?"),
            meta.get("generated_at", "?"),
        )

    return data["agents"], set(data.get("deactivate_slugs", []))


async def _seed_prompts(
    db: AsyncSession,
    prompts_data: list[dict],
    assignments_data: list[dict],
) -> int:
    """Seed reusable prompts and agent prompt assignments for a fresh DB."""
    created = 0
    agent_rows = (await db.execute(select(Agent))).scalars().all()
    agents_by_slug = {agent.slug: agent for agent in agent_rows}

    for prompt_data in prompts_data:
        slug = prompt_data["slug"]
        existing = (await db.execute(select(Prompt).where(Prompt.slug == slug))).scalar_one_or_none()
        if existing:
            logger.info("Prompt '%s' already exists, skipping", slug)
            continue
        owner_slug = prompt_data.get("owner_agent_slug")
        owner_agent = agents_by_slug.get(owner_slug) if owner_slug else None
        prompt = Prompt(
            slug=slug,
            name=prompt_data["name"],
            content=prompt_data["content"],
            description=prompt_data.get("description"),
            is_global=bool(prompt_data.get("is_global", False)),
            enabled=bool(prompt_data.get("enabled", True)),
            exclude_agents=prompt_data.get("exclude_agents", []),
            owner_agent_id=owner_agent.id if owner_agent else None,
            prompt_type=prompt_data.get("prompt_type", "standard"),
            deletion_locked=bool(prompt_data.get("deletion_locked", False)),
        )
        db.add(prompt)
        await db.flush()
        created += 1
        logger.info("Created prompt: %s", slug)

    prompts_by_slug = {
        prompt.slug: prompt
        for prompt in (await db.execute(select(Prompt))).scalars().all()
    }
    for assignment_data in assignments_data:
        agent = agents_by_slug.get(assignment_data.get("agent_slug"))
        prompt = prompts_by_slug.get(assignment_data.get("prompt_slug"))
        if agent is None or prompt is None:
            logger.warning("Skipping prompt assignment with missing agent/prompt: %s", assignment_data)
            continue
        existing = (
            await db.execute(
                select(AgentPrompt).where(
                    AgentPrompt.agent_id == agent.id,
                    AgentPrompt.prompt_id == prompt.id,
                )
            )
        ).scalar_one_or_none()
        if existing:
            continue
        db.add(
            AgentPrompt(
                agent_id=agent.id,
                prompt_id=prompt.id,
                role=assignment_data.get("role", "system"),
                priority=int(assignment_data.get("priority", 0)),
            )
        )

    return created


async def seed_agents(db: AsyncSession) -> int:
    """Seed default agents into database (insert-only, skips existing).

    Returns:
        Number of agents created
    """
    agents_data, deactivate_slugs = _load_seed_data()
    raw_seed = json.loads(SEED_FILE.read_text())
    prompts_data = raw_seed.get("prompts", [])
    assignments_data = raw_seed.get("agent_prompt_assignments", [])
    created_agents = 0

    for agent_data in agents_data:
        slug = agent_data["slug"]
        result = await db.execute(select(Agent).where(Agent.slug == slug))
        existing = result.scalar_one_or_none()

        if existing:
            logger.info(f"Agent '{slug}' already exists, skipping")
            continue

        agent = Agent(
            slug=slug,
            name=agent_data["name"],
            description=agent_data.get("description"),
            system_prompt=agent_data["system_prompt"],
            primary_model_id=resolve_model(agent_data["primary_model_id"]),
            fallback_models=_canonicalize_model_chain(agent_data.get("fallback_models", [])),
            escalation_model_id=resolve_model(agent_data["escalation_model_id"]) if agent_data.get("escalation_model_id") else None,
            strategies=agent_data.get("strategies", {}),
            temperature=agent_data.get("temperature", 0.7),
            thinking_level=agent_data.get("thinking_level"),
            is_active=slug not in deactivate_slugs,
            is_coding_agent=agent_data.get("is_coding_agent", False),
            memory_config=agent_data.get("memory_config"),
            version=1,
        )
        db.add(agent)
        await db.flush()
        await sync_agent_system_prompt(
            db,
            agent=agent,
            system_prompt=agent_data["system_prompt"],
            change_reason="Seed default agent system prompt",
        )
        created_agents += 1
        logger.info(f"Created agent: {slug}")

    if prompts_data or assignments_data:
        created_prompts = await _seed_prompts(db, prompts_data, assignments_data)
        if created_prompts:
            logger.info("Created prompts: %d", created_prompts)

    await db.commit()
    return created_agents


async def main() -> None:
    """Run the seed script."""
    db_url = settings.agent_hub_db_url.replace("postgresql://", "postgresql+asyncpg://")
    engine = create_async_engine(db_url)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)

    async with session_factory() as db:
        created = await seed_agents(db)
        logger.info(f"Seeded agents: {created} created")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
