"""Seed default agents into the database from seed_data.json.

Run with: python -m scripts.seed_agents

WARNING: This script is INSERT-ONLY by design. Do NOT add upsert/update logic.
The database is the source of truth for agent configuration (models, prompts,
temperatures, etc.). This script only bootstraps a fresh DB.

seed_data.json is AUTO-GENERATED by export_seeds.py. Never edit it by hand.
Use 'st prompt update' and the agent API for changes, then re-export.

To change agent config: use the UI, Alembic migrations, or direct DB updates.
Upsert logic was removed Feb 2026 after it silently overwrote manual model
assignments. See memory guardrail [G:8d98328d].
"""

import asyncio
import json
import logging
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings
from app.constants import resolve_model
from app.models import Agent
from app.services.owned_prompt_service import sync_agent_system_prompt

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)

SEED_FILE = Path(__file__).parent / "seed_agents_data" / "seed_data.json"


def _canonicalize_model_chain(models: list[str] | None) -> list[str]:
    seen: set[str] = set()
    canonical: list[str] = []
    for model in models or []:
        resolved = resolve_model(model)
        if not resolved or resolved in seen:
            continue
        seen.add(resolved)
        canonical.append(resolved)
    return canonical


def _load_seed_data() -> tuple[list[dict], list[str]]:
    """Load agents and deactivation list from seed_data.json."""
    if not SEED_FILE.exists():
        logger.error("seed_data.json not found at %s", SEED_FILE)
        logger.error("Run 'python -m scripts.export_seeds' to generate it from the database.")
        raise FileNotFoundError(SEED_FILE)

    data = json.loads(SEED_FILE.read_text())

    if "_metadata" in data:
        meta = data["_metadata"]
        logger.info(
            "Loading seed data: %d agents (exported %s)",
            meta.get("agent_count", "?"),
            meta.get("generated_at", "?"),
        )

    return data["agents"], data.get("deactivate_slugs", [])


async def seed_agents(db: AsyncSession) -> int:
    """Seed default agents into database (insert-only, skips existing).

    Returns:
        Number of agents created
    """
    agents_data, deactivate_slugs = _load_seed_data()
    created = 0

    for agent_data in agents_data:
        slug = agent_data["slug"]
        result = await db.execute(select(Agent).where(Agent.slug == slug))
        existing = result.scalar_one_or_none()

        if existing:
            logger.info(f"Agent '{slug}' already exists, skipping")
            continue

        agent = Agent(
            slug=slug,
            name=agent_data["name"],
            description=agent_data.get("description"),
            system_prompt=agent_data["system_prompt"],
            primary_model_id=resolve_model(agent_data["primary_model_id"]),
            fallback_models=_canonicalize_model_chain(agent_data.get("fallback_models", [])),
            escalation_model_id=resolve_model(agent_data["escalation_model_id"]) if agent_data.get("escalation_model_id") else None,
            strategies=agent_data.get("strategies", {}),
            temperature=agent_data.get("temperature", 0.7),
            thinking_level=agent_data.get("thinking_level"),
            is_active=True,
            is_coding_agent=agent_data.get("is_coding_agent", False),
            memory_config=agent_data.get("memory_config"),
            version=1,
        )
        db.add(agent)
        await db.flush()
        await sync_agent_system_prompt(
            db,
            agent=agent,
            system_prompt=agent_data["system_prompt"],
            change_reason="Seed default agent system prompt",
        )
        created += 1
        logger.info(f"Created agent: {slug}")

    # Deactivate absorbed agents
    for slug in deactivate_slugs:
        result = await db.execute(select(Agent).where(Agent.slug == slug))
        deactivate_agent = result.scalar_one_or_none()
        if deactivate_agent and deactivate_agent.is_active:
            deactivate_agent.is_active = False
            deactivate_agent.version += 1
            logger.info(f"Deactivated agent: {slug}")

    await db.commit()
    return created


async def main() -> None:
    """Run the seed script."""
    db_url = settings.agent_hub_db_url.replace("postgresql://", "postgresql+asyncpg://")
    engine = create_async_engine(db_url)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)

    async with session_factory() as db:
        created = await seed_agents(db)
        logger.info(f"Seeded agents: {created} created")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
