"""Canonical prompt slugs used by runtime workflows and UI."""

PLATFORM_CONTEXT_PROMPT_SLUG = "platform-context"
PERSONA_HEARTBEAT_PROMPT_SLUG = "persona-heartbeat-orchestrator"
PERSONA_HEARTBEAT_INSTRUCTIONS_PROMPT_SLUG = "persona-heartbeat-instructions"
PERSONA_FOCUS_HARNESS_PROMPT_SLUG = "persona-focus-harness"
PERSONA_WAKE_GUIDANCE_PROMPT_SLUG = "persona-wake-guidance"
PERSONA_ONBOARDING_BOOTSTRAP_PROMPT_SLUG = "persona-onboarding-bootstrap"
PERSONA_ONBOARDING_CONTINUATION_PROMPT_SLUG = "persona-onboarding-continuation"
PERSONA_ONBOARDING_PENDING_APPROVAL_PROMPT_SLUG = "persona-onboarding-pending-approval"
PERSONA_ONBOARDING_REVIEW_PROMPT_SLUG = "persona-onboarding-review"
PERSONA_EVOLUTION_GUIDELINES_PROMPT_SLUG = "persona-evolution-guidelines"
COMPLETION_REVIEW_PROMPT_SLUG = "completion-review-prompt"
COMPLETION_REVIEW_RULES_PROMPT_SLUG = "completion-review-rules"

__all__ = [
    "COMPLETION_REVIEW_PROMPT_SLUG",
    "COMPLETION_REVIEW_RULES_PROMPT_SLUG",
    "PERSONA_EVOLUTION_GUIDELINES_PROMPT_SLUG",
    "PERSONA_FOCUS_HARNESS_PROMPT_SLUG",
    "PERSONA_HEARTBEAT_INSTRUCTIONS_PROMPT_SLUG",
    "PERSONA_HEARTBEAT_PROMPT_SLUG",
    "PERSONA_ONBOARDING_BOOTSTRAP_PROMPT_SLUG",
    "PERSONA_ONBOARDING_CONTINUATION_PROMPT_SLUG",
    "PERSONA_ONBOARDING_PENDING_APPROVAL_PROMPT_SLUG",
    "PERSONA_ONBOARDING_REVIEW_PROMPT_SLUG",
    "PERSONA_WAKE_GUIDANCE_PROMPT_SLUG",
    "PLATFORM_CONTEXT_PROMPT_SLUG",
]
