"""add_provider_metadata_to_sessions

Revision ID: 1c6805054b00
Revises: 17cdcc56e5bd
Create Date: 2026-01-06 16:32:19.544668

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c6805054b00"
down_revision: str | Sequence[str] | None = "17cdcc56e5bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("provider_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "provider_metadata")
    # ### end Alembic commands ###
