"""drop_unused_session_columns

Revision ID: 1d642bcb1f01
Revises: cb33d77516d8
Create Date: 2026-02-02 16:21:54.131873

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d642bcb1f01"
down_revision: str | Sequence[str] | None = "cb33d77516d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_is_legacy"), table_name="sessions")
    op.drop_column("sessions", "continuation_count")
    op.drop_column("sessions", "is_legacy")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "is_legacy",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "continuation_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_sessions_is_legacy"), "sessions", ["is_legacy"], unique=False)
    # ### end Alembic commands ###
