"""drop_unused_columns

Revision ID: cb33d77516d8
Revises: w2x3y4z5a6b7
Create Date: 2026-02-02 13:53:31.620406

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb33d77516d8"
down_revision: str | Sequence[str] | None = "w2x3y4z5a6b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roundtable_messages_session_agent"), table_name="roundtable_messages")
    op.drop_index(op.f("ix_roundtable_messages_session_created"), table_name="roundtable_messages")
    op.drop_table("roundtable_messages")
    op.drop_index(op.f("ix_roundtable_sessions_project_created"), table_name="roundtable_sessions")
    op.drop_index(op.f("ix_roundtable_sessions_project_id"), table_name="roundtable_sessions")
    op.drop_table("roundtable_sessions")
    op.drop_index(op.f("ix_tier_change_log_created_at"), table_name="tier_change_log")
    op.drop_index(op.f("ix_tier_change_log_episode_uuid"), table_name="tier_change_log")
    op.drop_table("tier_change_log")
    op.drop_index(op.f("ix_message_feedback_message"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_message_id"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_session"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_type"), table_name="message_feedback")
    op.drop_table("message_feedback")
    op.drop_index(op.f("ix_global_instructions_scope"), table_name="global_instructions")
    op.drop_table("global_instructions")
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_column("memory_settings", "max_references")
    op.drop_constraint(op.f("request_logs_session_id_fkey"), "request_logs", type_="foreignkey")
    op.create_index(
        op.f("ix_sessions_parent_session_id"), "sessions", ["parent_session_id"], unique=False
    )
    op.drop_column("sessions", "task_outcome")
    op.drop_column("webhook_subscriptions", "last_triggered_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webhook_subscriptions",
        sa.Column(
            "last_triggered_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "task_outcome",
            postgresql.ENUM("passed", "failed", name="task_outcome_enum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_sessions_parent_session_id"), table_name="sessions")
    op.create_foreign_key(
        op.f("request_logs_session_id_fkey"),
        "request_logs",
        "sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "memory_settings",
        sa.Column(
            "max_references",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "verbosity",
            postgresql.ENUM("concise", "normal", "detailed", name="verbosity_level"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tone",
            postgresql.ENUM("professional", "friendly", "technical", name="tone_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("default_model", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_preferences_pkey")),
    )
    op.create_index(
        op.f("ix_user_preferences_user_id"), "user_preferences", ["user_id"], unique=True
    )
    op.create_table(
        "global_instructions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "content",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("global_instructions_pkey")),
    )
    op.create_index(
        op.f("ix_global_instructions_scope"), "global_instructions", ["scope"], unique=True
    )
    op.create_table(
        "message_feedback",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
        sa.Column(
            "feedback_type",
            postgresql.ENUM("positive", "negative", name="feedback_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("category", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "referenced_rule_uuids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("message_feedback_session_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("message_feedback_pkey")),
    )
    op.create_index(
        op.f("ix_message_feedback_type"), "message_feedback", ["feedback_type"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_session"), "message_feedback", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_message_id"), "message_feedback", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_message"), "message_feedback", ["message_id"], unique=False
    )
    op.create_table(
        "tier_change_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("episode_uuid", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("old_tier", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("new_tier", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("change_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tier_change_log_pkey")),
    )
    op.create_index(
        op.f("ix_tier_change_log_episode_uuid"), "tier_change_log", ["episode_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_tier_change_log_created_at"), "tier_change_log", ["created_at"], unique=False
    )
    op.create_table(
        "roundtable_sessions",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "mode",
            postgresql.ENUM("quick", "deliberation", name="roundtable_mode"),
            server_default=sa.text("'quick'::roundtable_mode"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tool_mode",
            postgresql.ENUM("read_only", "yolo", name="roundtable_tool_mode"),
            server_default=sa.text("'read_only'::roundtable_tool_mode"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("active", "completed", "failed", name="roundtable_status"),
            server_default=sa.text("'active'::roundtable_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("memory_group_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="roundtable_sessions_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_roundtable_sessions_project_id"),
        "roundtable_sessions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_roundtable_sessions_project_created"),
        "roundtable_sessions",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "roundtable_messages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("agent_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("model", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["roundtable_sessions.id"],
            name=op.f("roundtable_messages_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("roundtable_messages_pkey")),
    )
    op.create_index(
        op.f("ix_roundtable_messages_session_created"),
        "roundtable_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_roundtable_messages_session_agent"),
        "roundtable_messages",
        ["session_id", "agent_type"],
        unique=False,
    )
    # ### end Alembic commands ###
