"""add_purpose_and_session_type

Revision ID: ed13ea976211
Revises: 27229f433f34
Create Date: 2026-01-12 13:52:43.058963

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed13ea976211"
down_revision: str | Sequence[str] | None = "27229f433f34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type first
    session_type_enum = sa.Enum(
        "completion", "chat", "roundtable", "image_generation", name="session_type_enum"
    )
    session_type_enum.create(op.get_bind(), checkfirst=True)

    # Add purpose column (nullable)
    op.add_column("sessions", sa.Column("purpose", sa.String(length=100), nullable=True))

    # Add session_type with default for existing rows
    op.add_column(
        "sessions",
        sa.Column("session_type", session_type_enum, nullable=False, server_default="completion"),
    )

    op.create_index(op.f("ix_sessions_purpose"), "sessions", ["purpose"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_purpose"), table_name="sessions")
    op.drop_column("sessions", "session_type")
    op.drop_column("sessions", "purpose")
    # ### end Alembic commands ###
