"""Shared constants used across the application.

This module re-exports all constants from submodules for backward compatibility.
Everything that was importable from app.constants before remains importable.
"""

from __future__ import annotations

# Re-export catalog structures and functions
from app.constants.catalog import (
    CLAUDE_TO_GEMINI_MAP,
    CODEX_TO_CLAUDE_MAP,
    GEMINI_TO_CLAUDE_MAP,
    MINIMAX_TO_CLAUDE_MAP,
    MODEL_ALIASES,
    MODEL_CATALOG,
    MODEL_CATALOG_BY_ID,
    MODEL_REGISTRY,
    NVIDIA_TO_CLAUDE_MAP,
    OPENAI_TO_CLAUDE_MAP,
    SCORE_WEIGHTS,
    VALID_CLAUDE_MODELS,
    VALID_CODEX_MODELS,
    VALID_GEMINI_MODELS,
    VALID_MINIMAX_MODELS,
    VALID_NVIDIA_MODELS,
    VALID_OPENAI_MODELS,
    VALID_XAI_MODELS,
    VALID_ZHIPU_MODELS,
    XAI_TO_CLAUDE_MAP,
    ZHIPU_TO_CLAUDE_MAP,
    ModelCapabilities,
    ModelCost,
    ModelEntry,
    ModelScores,
    resolve_model,
)

# Re-export model ID constants
from app.constants.models import (
    CLAUDE_HAIKU,
    CLAUDE_OPUS,
    CLAUDE_SONNET,
    CODEX_GPT_5_1,
    CODEX_GPT_5_1_MINI,
    CODEX_GPT_5_2,
    CODEX_GPT_5_3,
    CODEX_GPT_5_3_SPARK,
    CODEX_GPT_5_4,
    DEFAULT_CLAUDE_MODEL,
    DEFAULT_GEMINI_MODEL,
    FAST_CLAUDE_MODEL,
    FAST_GEMINI_MODEL,
    GEMINI_2_5_FLASH_LITE,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_PRO,
    GEMINI_FLASH,
    GEMINI_IMAGE,
    GEMINI_IMAGE_NANO,
    GEMINI_IMAGE_NANO2,
    GEMINI_PRO,
    MINIMAX_IMAGE_01,
    MINIMAX_M2_5,
    NVIDIA_FLUX_1_DEV,
    NVIDIA_FLUX_1_KONTEXT,
    NVIDIA_FLUX_1_SCHNELL,
    NVIDIA_KIMI_K2_5,
    NVIDIA_MINIMAX_M2_5,
    NVIDIA_QWEN_3_5,
    NVIDIA_SD_3_5_LARGE,
    OPENAI_GPT_5_2,
    OPENAI_GPT_NANO,
    OR_FREE_GLM,
    OR_FREE_TRINITY,
    OR_KIMI_K2_5,
    PROVIDER_NAMES,
    REASONING_CLAUDE_MODEL,
    REASONING_GEMINI_MODEL,
    XAI_GROK_4_1_FAST,
    XAI_GROK_4_20,
    XAI_GROK_4_20_MULTI_AGENT,
    XAI_GROK_CODE_FAST,
    ZHIPU_GLM_4_7,
    ZHIPU_GLM_5,
)

# Re-export project constants
from app.constants.projects import VALID_AGENT_TYPES, VALID_PROJECT_IDS
from app.constants.subtask_types import (
    SUBTASK_TYPE_DESCRIPTIONS,
    SUBTASK_TYPES,
    format_subtask_types_markdown,
)

# Rate limiting defaults
DEFAULT_RATE_LIMIT_TPM = 100_000

__all__ = [
    "CLAUDE_HAIKU",
    "CLAUDE_OPUS",
    "CLAUDE_SONNET",
    "CLAUDE_TO_GEMINI_MAP",
    "CODEX_GPT_5_1",
    "CODEX_GPT_5_1_MINI",
    "CODEX_GPT_5_2",
    "CODEX_GPT_5_3",
    "CODEX_GPT_5_3_SPARK",
    "CODEX_GPT_5_4",
    "CODEX_TO_CLAUDE_MAP",
    "DEFAULT_CLAUDE_MODEL",
    "DEFAULT_GEMINI_MODEL",
    "DEFAULT_RATE_LIMIT_TPM",
    "FAST_CLAUDE_MODEL",
    "FAST_GEMINI_MODEL",
    "GEMINI_2_5_FLASH_LITE",
    "GEMINI_3_1_FLASH_LITE",
    "GEMINI_3_1_PRO",
    "GEMINI_FLASH",
    "GEMINI_IMAGE",
    "GEMINI_IMAGE_NANO",
    "GEMINI_IMAGE_NANO2",
    "GEMINI_PRO",
    "GEMINI_TO_CLAUDE_MAP",
    "MINIMAX_IMAGE_01",
    "MINIMAX_M2_5",
    "MINIMAX_TO_CLAUDE_MAP",
    "MODEL_ALIASES",
    "MODEL_CATALOG",
    "MODEL_CATALOG_BY_ID",
    "MODEL_REGISTRY",
    "NVIDIA_FLUX_1_DEV",
    "NVIDIA_FLUX_1_KONTEXT",
    "NVIDIA_FLUX_1_SCHNELL",
    "NVIDIA_KIMI_K2_5",
    "NVIDIA_MINIMAX_M2_5",
    "NVIDIA_QWEN_3_5",
    "NVIDIA_SD_3_5_LARGE",
    "NVIDIA_TO_CLAUDE_MAP",
    "OPENAI_GPT_5_2",
    "OPENAI_GPT_NANO",
    "OPENAI_TO_CLAUDE_MAP",
    "OR_FREE_GLM",
    "OR_FREE_TRINITY",
    "OR_KIMI_K2_5",
    "PROVIDER_NAMES",
    "REASONING_CLAUDE_MODEL",
    "REASONING_GEMINI_MODEL",
    "SCORE_WEIGHTS",
    "SUBTASK_TYPES",
    "SUBTASK_TYPE_DESCRIPTIONS",
    "VALID_AGENT_TYPES",
    "VALID_CLAUDE_MODELS",
    "VALID_CODEX_MODELS",
    "VALID_GEMINI_MODELS",
    "VALID_MINIMAX_MODELS",
    "VALID_NVIDIA_MODELS",
    "VALID_OPENAI_MODELS",
    "VALID_PROJECT_IDS",
    "VALID_XAI_MODELS",
    "VALID_ZHIPU_MODELS",
    "XAI_GROK_4_1_FAST",
    "XAI_GROK_4_20",
    "XAI_GROK_4_20_MULTI_AGENT",
    "XAI_GROK_CODE_FAST",
    "XAI_TO_CLAUDE_MAP",
    "ZHIPU_GLM_4_7",
    "ZHIPU_GLM_5",
    "ZHIPU_TO_CLAUDE_MAP",
    "ModelCapabilities",
    "ModelCost",
    "ModelEntry",
    "ModelScores",
    "format_subtask_types_markdown",
    "resolve_model",
]
