"""Shared constants used across the application.

This module re-exports constants from submodules for backward compatibility.
"""
# ruff: noqa: F401

from __future__ import annotations

from app.constants.catalog import (
    CLAUDE_TO_GEMINI_MAP,
    CLOUDFLARE_TO_CLAUDE_MAP,
    CODEX_TO_CLAUDE_MAP,
    DEEPSEEK_TO_CLAUDE_MAP,
    GEMINI_TO_CLAUDE_MAP,
    LOCAL_TO_CLAUDE_MAP,
    MINIMAX_TO_CLAUDE_MAP,
    MODEL_ALIASES,
    MODEL_CATALOG,
    MODEL_CATALOG_BY_ID,
    MODEL_REGISTRY,
    MOONSHOT_TO_CLAUDE_MAP,
    NVIDIA_TO_CLAUDE_MAP,
    OPENAI_TO_CLAUDE_MAP,
    SCORE_WEIGHTS,
    VALID_CLAUDE_MODELS,
    VALID_CLOUDFLARE_MODELS,
    VALID_CODEX_MODELS,
    VALID_DEEPSEEK_MODELS,
    VALID_GEMINI_MODELS,
    VALID_KIMI_CODE_MODELS,
    VALID_LOCAL_MODELS,
    VALID_MINIMAX_MODELS,
    VALID_MOONSHOT_MODELS,
    VALID_NVIDIA_MODELS,
    VALID_OPENAI_MODELS,
    VALID_OPENROUTER_MODELS,
    VALID_XAI_MODELS,
    VALID_ZHIPU_MODELS,
    XAI_TO_CLAUDE_MAP,
    ZHIPU_TO_CLAUDE_MAP,
    ModelCapabilities,
    ModelCost,
    ModelEntry,
    ModelScores,
    get_model_capabilities,
    get_model_entry,
    resolve_model,
)
from app.constants.models import (
    CF_FLUX_1_SCHNELL,
    CF_FLUX_2_DEV,
    CF_GEMMA_4_26B,
    CF_GLM_4_7_FLASH,
    CF_GPT_OSS_20B,
    CF_GPT_OSS_120B,
    CF_GRANITE_4_H_MICRO,
    CF_KIMI_K2_5,
    CF_KIMI_K2_6,
    CF_LEONARDO_LUCID,
    CF_LEONARDO_PHOENIX,
    CF_LLAMA_4_SCOUT,
    CF_MISTRAL_SMALL,
    CF_NEMOTRON_3_120B,
    CF_QWEN2_5_CODER,
    CF_QWEN3_30B,
    CF_QWQ_32B,
    CF_SD_XL_LIGHTNING,
    CLAUDE_HAIKU,
    CLAUDE_OPUS,
    CLAUDE_OPUS_4_7,
    CLAUDE_SONNET,
    CODEX_GPT_5_1,
    CODEX_GPT_5_1_MINI,
    CODEX_GPT_5_2,
    CODEX_GPT_5_3,
    CODEX_GPT_5_3_SPARK,
    CODEX_GPT_5_4,
    CODEX_GPT_5_4_MINI,
    CODEX_GPT_5_5,
    DEEPSEEK_V4_FLASH,
    DEEPSEEK_V4_PRO,
    DEFAULT_GEMINI_MODEL,
    FAST_GEMINI_MODEL,
    GEMINI_2_5_FLASH_LITE,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_PRO,
    GEMINI_FLASH,
    GEMINI_IMAGE,
    GEMINI_IMAGE_NANO,
    GEMINI_IMAGE_NANO2,
    KIMI_CODE_FOR_CODING,
    LOCAL_QWEN2_5_CODER_14B,
    LOCAL_QWEN3_30B_A3B,
    LOCAL_QWEN3_CODER_30B_A3B,
    MINIMAX_IMAGE_01,
    MINIMAX_M2_5,
    MINIMAX_M2_5_HIGHSPEED,
    MINIMAX_M2_7,
    MINIMAX_M2_7_HIGHSPEED,
    MOONSHOT_KIMI_K2_5,
    MOONSHOT_KIMI_K2_6,
    NVIDIA_DEEPSEEK_V4_FLASH,
    NVIDIA_FLUX_1_DEV,
    NVIDIA_FLUX_1_KONTEXT,
    NVIDIA_FLUX_1_SCHNELL,
    NVIDIA_KIMI_K2_5,
    NVIDIA_KIMI_K2_6,
    NVIDIA_MINIMAX_M2_5,
    NVIDIA_MINIMAX_M2_7,
    NVIDIA_QWEN_3_5,
    NVIDIA_SD_3_5_LARGE,
    OPENAI_GPT_5_2,
    OPENAI_GPT_5_2_PRO,
    OPENAI_GPT_5_4,
    OPENAI_GPT_5_4_MINI,
    OPENAI_GPT_5_4_NANO,
    OPENAI_GPT_5_4_PRO,
    OPENAI_GPT_5_5,
    OPENAI_GPT_NANO,
    OR_FREE_GLM,
    OR_FREE_TRINITY,
    OR_KIMI_K2_5,
    OR_KIMI_K2_6,
    PROVIDER_NAMES,
    REASONING_GEMINI_MODEL,
    XAI_GROK_4_3,
    XAI_GROK_4_20,
    XAI_GROK_4_20_MULTI_AGENT,
    ZHIPU_GLM_4_7,
    ZHIPU_GLM_4_7_FLASH,
    ZHIPU_GLM_4_7_FLASHX,
    ZHIPU_GLM_5,
    ZHIPU_GLM_5_1,
    ZHIPU_GLM_5_TURBO,
)
from app.constants.projects import VALID_AGENT_TYPES, VALID_PROJECT_IDS
from app.constants.subtask_types import (
    SUBTASK_TYPE_DESCRIPTIONS,
    SUBTASK_TYPES,
    format_subtask_types_markdown,
)

DEFAULT_RATE_LIMIT_TPM = 100_000

__all__ = [
    name
    for name in globals()
    if (
        name.isupper()
        or name in {
            "ModelCapabilities",
            "ModelCost",
            "ModelEntry",
            "ModelScores",
            "format_subtask_types_markdown",
            "get_model_capabilities",
            "get_model_entry",
            "resolve_model",
        }
    )
]
