"""Model catalog entries — single source of truth for all registered models."""

from __future__ import annotations

from app.constants.catalog_types import (
    ModelCapabilities,
    ModelCost,
    ModelEntry,
    ModelScores,
)
from app.constants.models import (
    CF_FLUX_1_SCHNELL,
    CF_FLUX_2_DEV,
    CF_LEONARDO_LUCID,
    CF_LEONARDO_PHOENIX,
    CF_LLAMA_4_SCOUT,
    CF_MISTRAL_SMALL,
    CF_QWEN2_5_CODER,
    CF_QWEN3_30B,
    CF_QWQ_32B,
    CF_SD_XL_LIGHTNING,
    CLAUDE_HAIKU,
    CLAUDE_OPUS,
    CLAUDE_OPUS_4_7,
    CLAUDE_SONNET,
    CODEX_GPT_5_1,
    CODEX_GPT_5_1_MINI,
    CODEX_GPT_5_2,
    CODEX_GPT_5_3,
    CODEX_GPT_5_3_SPARK,
    CODEX_GPT_5_4,
    CODEX_GPT_5_5,
    GEMINI_2_5_FLASH_LITE,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_PRO,
    GEMINI_FLASH,
    GEMINI_IMAGE,
    GEMINI_IMAGE_NANO,
    GEMINI_IMAGE_NANO2,
    GEMINI_PRO,
    MINIMAX_IMAGE_01,
    MINIMAX_M2_5,
    NVIDIA_FLUX_1_DEV,
    NVIDIA_FLUX_1_KONTEXT,
    NVIDIA_FLUX_1_SCHNELL,
    NVIDIA_KIMI_K2_5,
    NVIDIA_MINIMAX_M2_5,
    NVIDIA_QWEN_3_5,
    NVIDIA_SD_3_5_LARGE,
    OPENAI_GPT_5_2,
    OPENAI_GPT_NANO,
    OR_FREE_GLM,
    OR_FREE_TRINITY,
    OR_KIMI_K2_5,
    XAI_GROK_4_1_FAST,
    XAI_GROK_4_20,
    XAI_GROK_4_20_MULTI_AGENT,
    XAI_GROK_CODE_FAST,
    ZHIPU_GLM_4_7,
    ZHIPU_GLM_5,
)

# Single place to register UI-visible models. Everything else derives from this.
# Scores sourced from SWE-Bench, GPQA Diamond, BFCL, IFEval, MMMU-Pro, etc.
MODEL_CATALOG: list[ModelEntry] = [
    # --- Claude (4) ---
    ModelEntry(
        id=CLAUDE_SONNET, alias="sonnet", name="Claude Sonnet 4.6",
        hint="Balanced", provider="claude",
        scores=ModelScores(coding=80, reasoning=87, planning=72, tool_use=78, instruction=84, design=72),
        cost=ModelCost(3.00, 15.00, cache_read_per_million=0.30, cache_write_per_million=3.75),
        context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_pdf=True,
            supports_tool_execution=True,
            max_output_tokens=16384,
        ),
        release_date="2026-01-29", knowledge_cutoff="2025-05-01", family="claude-sonnet",
    ),
    ModelEntry(
        id=CLAUDE_OPUS, alias="opus", name="Claude Opus 4.6",
        hint="Powerful", provider="claude",
        scores=ModelScores(coding=80, reasoning=91, planning=70, tool_use=75, instruction=85, design=70),
        cost=ModelCost(5.00, 25.00, cache_read_per_million=0.50, cache_write_per_million=6.25),
        context_window=1_000_000, speed_tier="slow",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_pdf=True,
            supports_tool_execution=True,
            max_output_tokens=32768,
        ),
        release_date="2026-01-29", knowledge_cutoff="2025-05-01", family="claude-opus",
    ),
    ModelEntry(
        id=CLAUDE_OPUS_4_7, alias="opus-4.7", name="Claude Opus 4.7",
        hint="Most capable", provider="claude",
        scores=ModelScores(coding=85, reasoning=93, planning=74, tool_use=78, instruction=86, design=72),
        cost=ModelCost(5.00, 25.00, cache_read_per_million=0.50, cache_write_per_million=6.25),
        context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_pdf=True,
            supports_tool_execution=True,
            max_output_tokens=131072,
        ),
        knowledge_cutoff="2026-01-01", family="claude-opus",
    ),
    ModelEntry(
        id=CLAUDE_HAIKU, alias="haiku", name="Claude Haiku 4.5",
        hint="Quick", provider="claude",
        scores=ModelScores(coding=73, reasoning=70, planning=50, tool_use=65, instruction=65, design=60),
        cost=ModelCost(1.00, 5.00, cache_read_per_million=0.10, cache_write_per_million=1.25),
        context_window=200_000, speed_tier="fast",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_pdf=True,
            supports_tool_execution=True,
            max_output_tokens=8192,
        ),
        release_date="2025-10-01", knowledge_cutoff="2025-04-01", family="claude-haiku",
    ),
    # --- Gemini (4) ---
    ModelEntry(
        id=GEMINI_FLASH, alias="flash", name="Gemini 3 Flash",
        hint="Fast", provider="gemini",
        scores=ModelScores(coding=78, reasoning=90, planning=72, tool_use=75, instruction=83, design=85),
        cost=ModelCost(0.50, 3.00), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(
            can_generate_images=True,
            has_vision=True,
            can_edit_images=True,
            has_thinking=True,
            supports_pdf=True,
            supports_audio=True,
            supports_tool_execution=True,
            max_output_tokens=65536,
        ),
        release_date="2025-12-11", knowledge_cutoff="2025-09-01", family="gemini-flash",
    ),
    ModelEntry(
        id=GEMINI_2_5_FLASH_LITE, alias="flash-lite", name="Gemini 2.5 Flash Lite",
        hint="Cheap", provider="gemini",
        scores=ModelScores(coding=34, reasoning=50, planning=40, tool_use=45, instruction=84, design=55),
        cost=ModelCost(0.10, 0.40), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_pdf=True, max_output_tokens=8192),
        release_date="2025-06-01", knowledge_cutoff="2025-01-01", family="gemini-flash-lite",
    ),
    ModelEntry(
        id=GEMINI_3_1_FLASH_LITE, alias="3.1-flash-lite", name="Gemini 3.1 Flash Lite",
        hint="High Throughput", provider="gemini",
        scores=ModelScores(coding=56, reasoning=64, planning=46, tool_use=49, instruction=86, design=58),
        cost=ModelCost(0.10, 0.40), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_pdf=True, max_output_tokens=8192),
        release_date="2026-01-15", knowledge_cutoff="2025-11-01", family="gemini-flash-lite",
    ),
    ModelEntry(
        id=GEMINI_PRO, alias="pro", name="Gemini 3 Pro",
        hint="Reasoning", provider="gemini",
        scores=ModelScores(coding=76, reasoning=92, planning=75, tool_use=78, instruction=85, design=88),
        cost=ModelCost(3.00, 15.00), context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, has_vision=True, can_edit_images=True, has_thinking=True, supports_pdf=True, supports_audio=True, max_output_tokens=65536),
        release_date="2025-12-11", knowledge_cutoff="2025-09-01", family="gemini-pro",
    ),
    ModelEntry(
        id=GEMINI_3_1_PRO, alias="3.1-pro", name="Gemini 3.1 Pro",
        hint="Deep Reasoning", provider="gemini",
        scores=ModelScores(coding=82, reasoning=96, planning=82, tool_use=82, instruction=88, design=90),
        cost=ModelCost(3.00, 15.00), context_window=1_000_000, speed_tier="slow",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_pdf=True,
            supports_audio=True,
            supports_tool_execution=True,
            max_output_tokens=65536,
        ),
        release_date="2026-02-01", knowledge_cutoff="2025-11-01", family="gemini-pro",
    ),
    # --- Gemini Image Models (3) ---
    ModelEntry(
        id=GEMINI_IMAGE, alias="pro-image", name="Gemini 3 Pro Image",
        hint="Image Gen", provider="gemini",
        scores=ModelScores(coding=20, reasoning=40, planning=30, tool_use=25, instruction=60, design=92),
        cost=ModelCost(3.00, 15.00), context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, has_vision=True, can_edit_images=True, max_output_tokens=8192),
        release_date="2025-12-11", family="gemini-image",
    ),
    ModelEntry(
        id=GEMINI_IMAGE_NANO, alias="nano-banana", name="Nano Banana",
        hint="Fast Image", provider="gemini",
        scores=ModelScores(coding=15, reasoning=30, planning=20, tool_use=20, instruction=50, design=80),
        cost=ModelCost(0.50, 3.00), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, has_vision=True, can_edit_images=True, max_output_tokens=8192),
        release_date="2025-06-01", family="gemini-image",
    ),
    ModelEntry(
        id=GEMINI_IMAGE_NANO2, alias="nano-banana-2", name="Nano Banana 2",
        hint="Fastest Image", provider="gemini",
        scores=ModelScores(coding=15, reasoning=35, planning=22, tool_use=22, instruction=55, design=85),
        cost=ModelCost(0.50, 3.00), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, has_vision=True, can_edit_images=True, max_output_tokens=8192),
        release_date="2026-02-01", family="gemini-image",
    ),
    # --- OpenRouter (3) — cheaper/exclusive on OR ---
    ModelEntry(
        id=OR_KIMI_K2_5, alias="or/kimi", name="Kimi K2.5 (OR)",
        hint="Kimi K2.5", provider="openrouter",
        scores=ModelScores(coding=75, reasoning=88, planning=72, tool_use=80, instruction=83, design=82),
        cost=ModelCost(0.50, 2.00), context_window=200_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, max_output_tokens=16384),
        release_date="2025-12-01", family="kimi",
    ),
    ModelEntry(
        id=OR_FREE_TRINITY, alias="or/free-trinity", name="Trinity Large (Free)",
        hint="Trinity Free", provider="openrouter",
        scores=ModelScores(coding=55, reasoning=60, planning=45, tool_use=50, instruction=65, design=45),
        cost=ModelCost(0.00, 0.00), context_window=128_000, speed_tier="fast",
        family="trinity",
    ),
    ModelEntry(
        id=OR_FREE_GLM, alias="or/free-glm", name="GLM-4.5 Air (Free)",
        hint="GLM Free", provider="openrouter",
        scores=ModelScores(coding=60, reasoning=65, planning=50, tool_use=55, instruction=70, design=50),
        cost=ModelCost(0.00, 0.00), context_window=128_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True),
        family="glm",
    ),
    # --- OpenAI (2) ---
    ModelEntry(
        id=OPENAI_GPT_5_2, alias="gpt5.2", name="GPT-5.2",
        hint="GPT 5.2", provider="openai",
        scores=ModelScores(coding=80, reasoning=93, planning=75, tool_use=76, instruction=87, design=70),
        cost=ModelCost(2.00, 10.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, max_output_tokens=32768),
        release_date="2025-11-01", knowledge_cutoff="2025-06-01", family="gpt",
    ),
    ModelEntry(
        id=OPENAI_GPT_NANO, alias="nano", name="GPT-5 Nano",
        hint="Nano", provider="openai",
        scores=ModelScores(coding=40, reasoning=60, planning=35, tool_use=40, instruction=70, design=50),
        cost=ModelCost(0.05, 0.40, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, max_output_tokens=8192),
        release_date="2025-10-01", family="gpt-nano",
    ),
    # --- Codex (7) ---
    ModelEntry(
        id=CODEX_GPT_5_5, alias="codex", name="GPT-5.5 (Codex)",
        hint="Codex Frontier", provider="codex",
        scores=ModelScores(coding=98, reasoning=99, planning=90, tool_use=91, instruction=94, design=82),
        cost=ModelCost(0.00, 0.00),
        context_window=1_050_000, speed_tier="medium",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_pdf=True,
            supports_tool_execution=True,
            supports_verbosity=True,
            supports_xhigh=True,
            supports_session_cache=True,
            max_output_tokens=32768,
        ),
        release_date="2026-04-23", knowledge_cutoff="2026-01-01", family="gpt",
        availability="codex_only",
    ),
    ModelEntry(
        id=CODEX_GPT_5_4, alias="codex-5.4", name="GPT-5.4 (Codex)",
        hint="Frontier", provider="codex",
        scores=ModelScores(coding=95, reasoning=97, planning=85, tool_use=88, instruction=92, design=78),
        cost=ModelCost(2.50, 15.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=1_050_000, speed_tier="medium",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_pdf=True,
            supports_tool_execution=True,
            supports_verbosity=True,
            supports_xhigh=True,
            supports_session_cache=True,
            max_output_tokens=32768,
        ),
        release_date="2026-03-05", knowledge_cutoff="2025-12-01", family="gpt",
    ),
    ModelEntry(
        id=CODEX_GPT_5_3, alias="codex-5.3", name="GPT-5.3 Codex",
        hint="Best Coding", provider="codex",
        scores=ModelScores(coding=93, reasoning=95, planning=80, tool_use=80, instruction=90, design=72),
        cost=ModelCost(1.75, 14.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_tool_execution=True,
            supports_verbosity=True,
            supports_session_cache=True,
            max_output_tokens=32768,
        ),
        release_date="2026-02-05", knowledge_cutoff="2025-10-01", family="gpt-codex",
    ),
    ModelEntry(
        id=CODEX_GPT_5_3_SPARK, alias="codex-spark", name="GPT-5.3 Codex Spark",
        hint="Real-Time Coding", provider="codex",
        scores=ModelScores(coding=88, reasoning=88, planning=72, tool_use=72, instruction=85, design=68),
        cost=ModelCost(1.00, 8.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_tool_execution=True,
            supports_verbosity=True,
            supports_session_cache=True,
            max_output_tokens=16384,
        ),
        release_date="2026-02-12", knowledge_cutoff="2025-10-01", family="gpt-codex",
    ),
    ModelEntry(
        id=CODEX_GPT_5_2, alias="codex-5.2", name="GPT-5.2 Codex",
        hint="Coding Stable", provider="codex",
        scores=ModelScores(coding=90, reasoning=92, planning=78, tool_use=78, instruction=88, design=70),
        cost=ModelCost(2.00, 12.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="medium",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_tool_execution=True,
            supports_verbosity=True,
            supports_session_cache=True,
            max_output_tokens=32768,
        ),
        release_date="2026-01-01", knowledge_cutoff="2025-09-01", family="gpt-codex",
    ),
    ModelEntry(
        id=CODEX_GPT_5_1, alias="codex-5.1", name="GPT-5.1 Codex",
        hint="Fallback Coding", provider="codex",
        scores=ModelScores(coding=86, reasoning=89, planning=74, tool_use=74, instruction=84, design=68),
        cost=ModelCost(1.50, 10.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="medium",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_tool_execution=True,
            supports_verbosity=True,
            supports_session_cache=True,
            max_output_tokens=32768,
        ),
        release_date="2025-12-01", knowledge_cutoff="2025-08-01", family="gpt-codex",
    ),
    ModelEntry(
        id=CODEX_GPT_5_1_MINI, alias="codex-mini", name="GPT-5.1 Codex Mini",
        hint="Cheap Fallback", provider="codex",
        scores=ModelScores(coding=76, reasoning=80, planning=62, tool_use=66, instruction=78, design=62),
        cost=ModelCost(0.50, 2.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, max_output_tokens=16384),
        release_date="2025-12-01", knowledge_cutoff="2025-08-01", family="gpt-codex",
    ),
    # --- xAI (4) ---
    ModelEntry(
        id=XAI_GROK_CODE_FAST, alias="grok", name="Grok Code Fast 1",
        hint="Grok Code", provider="xai",
        scores=ModelScores(coding=71, reasoning=65, planning=60, tool_use=68, instruction=76, design=65),
        cost=ModelCost(0.20, 0.50), context_window=2_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_session_cache=True, max_output_tokens=16384),
        release_date="2025-11-01", family="grok",
    ),
    ModelEntry(
        id=XAI_GROK_4_1_FAST, alias="grok-fast", name="Grok 4.1 Fast",
        hint="Grok 4.1", provider="xai",
        scores=ModelScores(coding=68, reasoning=75, planning=82, tool_use=80, instruction=78, design=65),
        cost=ModelCost(0.20, 0.50), context_window=2_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_session_cache=True,
            max_output_tokens=16384,
        ),
        release_date="2026-01-01", family="grok",
    ),
    ModelEntry(
        id=XAI_GROK_4_20, alias="grok-4.20", name="Grok 4.20 Reasoning",
        hint="Flagship Reasoning", provider="xai",
        scores=ModelScores(coding=75, reasoning=88, planning=86, tool_use=84, instruction=84, design=72),
        cost=ModelCost(2.00, 6.00), context_window=2_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(
            has_vision=True,
            has_thinking=True,
            supports_tool_execution=True,
            supports_session_cache=True,
            max_output_tokens=32768,
        ),
        release_date="2026-03-10", knowledge_cutoff="2024-11-01", family="grok-4.20",
    ),
    ModelEntry(
        id=XAI_GROK_4_20_MULTI_AGENT, alias="grok-research", name="Grok 4.20 Multi-Agent",
        hint="Deep Research", provider="xai",
        scores=ModelScores(coding=72, reasoning=91, planning=94, tool_use=70, instruction=86, design=68),
        cost=ModelCost(2.00, 6.00), context_window=2_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(
            has_thinking=True,
            supports_session_cache=True,
            max_output_tokens=32768,
        ),
        release_date="2026-03-09", knowledge_cutoff="2024-11-01", family="grok-4.20",
    ),
    # --- Zhipu (2) ---
    ModelEntry(
        id=ZHIPU_GLM_5, alias="glm5", name="GLM-5",
        hint="GLM-5", provider="zhipu",
        scores=ModelScores(coding=78, reasoning=92, planning=70, tool_use=75, instruction=85, design=68),
        cost=ModelCost(0.90, 2.88), context_window=200_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, max_output_tokens=16384),
        release_date="2025-10-01", family="glm",
    ),
    ModelEntry(
        id=ZHIPU_GLM_4_7, alias="glm4.7", name="GLM-4.7",
        hint="GLM-4.7", provider="zhipu",
        scores=ModelScores(coding=74, reasoning=95, planning=67, tool_use=85, instruction=82, design=70),
        cost=ModelCost(0.35, 1.55), context_window=200_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, max_output_tokens=16384),
        release_date="2026-01-15", family="glm",
    ),
    # --- MiniMax (1) ---
    ModelEntry(
        id=MINIMAX_M2_5, alias="minimax", name="MiniMax M2.5",
        hint="Coding", provider="minimax",
        scores=ModelScores(coding=80, reasoning=85, planning=76, tool_use=77, instruction=84, design=60),
        cost=ModelCost(0.15, 1.20, cache_read_per_million=0.03),
        context_window=204_800, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, max_output_tokens=131_072),
        release_date="2026-02-12", knowledge_cutoff="2025-09-01", family="minimax",
    ),
    # --- NVIDIA NIM (3) — free tier via NVIDIA developer program ---
    ModelEntry(
        id=NVIDIA_QWEN_3_5, alias="nv/qwen", name="Qwen 3.5 397B (NVIDIA)",
        hint="Vision+Code", provider="nvidia",
        scores=ModelScores(coding=78, reasoning=90, planning=76, tool_use=73, instruction=77, design=85),
        cost=ModelCost(0.00, 0.00), context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, max_output_tokens=32_768),
        release_date="2026-02-16", knowledge_cutoff="2025-09-01", family="qwen",
    ),
    ModelEntry(
        id=NVIDIA_MINIMAX_M2_5, alias="nv/minimax", name="MiniMax M2.5 (NVIDIA)",
        hint="Free Coding", provider="nvidia",
        scores=ModelScores(coding=80, reasoning=85, planning=76, tool_use=77, instruction=84, design=60),
        cost=ModelCost(0.00, 0.00), context_window=204_800, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, max_output_tokens=131_072),
        release_date="2026-02-12", knowledge_cutoff="2025-09-01", family="minimax",
    ),
    ModelEntry(
        id=NVIDIA_KIMI_K2_5, alias="nv/kimi", name="Kimi K2.5 (NVIDIA)",
        hint="Multimodal", provider="nvidia",
        scores=ModelScores(coding=79, reasoning=90, planning=78, tool_use=82, instruction=83, design=82),
        cost=ModelCost(0.00, 0.00), context_window=256_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, max_output_tokens=32_768),
        release_date="2026-01-01", knowledge_cutoff="2025-09-01", family="kimi",
    ),
    # --- NVIDIA NIM Image Generation (4) — FLUX + Stable Diffusion via ai.api.nvidia.com ---
    ModelEntry(
        id=NVIDIA_FLUX_1_DEV, alias="nv/flux-dev", name="FLUX.1-dev (NVIDIA)",
        hint="Image Gen", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=40, design=88),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="slow",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-12-01", family="flux",
    ),
    ModelEntry(
        id=NVIDIA_FLUX_1_SCHNELL, alias="nv/flux-schnell", name="FLUX.1-schnell (NVIDIA)",
        hint="Fast Image", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=35, design=82),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-12-01", family="flux",
    ),
    ModelEntry(
        id=NVIDIA_SD_3_5_LARGE, alias="nv/sd3.5", name="Stable Diffusion 3.5 Large (NVIDIA)",
        hint="Image Gen", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=38, design=85),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-10-01", family="stable-diffusion",
    ),
    ModelEntry(
        id=NVIDIA_FLUX_1_KONTEXT, alias="nv/flux-kontext", name="FLUX.1-Kontext (NVIDIA)",
        hint="Image Edit", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=50, design=90),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, can_edit_images=True, max_output_tokens=0),
        release_date="2025-06-01", family="flux",
    ),
    # --- MiniMax Image Generation (1) — image-01 via api.minimax.io ---
    ModelEntry(
        id=MINIMAX_IMAGE_01, alias="mm/image-01", name="MiniMax Image-01",
        hint="Image Gen", provider="minimax",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=35, design=80),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.0035), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2025-02-15", family="minimax-image",
    ),
    # --- Cloudflare Workers AI LLM (5) — free tier 10k Neurons/day ---
    ModelEntry(
        id=CF_LLAMA_4_SCOUT, alias="cf/llama", name="Llama 4 Scout 17B (CF)",
        hint="Multimodal", provider="cloudflare",
        scores=ModelScores(coding=55, reasoning=60, planning=50, tool_use=50, instruction=65, design=55),
        cost=ModelCost(0.00, 0.00), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, max_output_tokens=8192),
        release_date="2025-04-01", family="llama",
    ),
    ModelEntry(
        id=CF_QWEN3_30B, alias="cf/qwen3", name="Qwen3 30B (CF)",
        hint="Thinking", provider="cloudflare",
        scores=ModelScores(coding=60, reasoning=70, planning=55, tool_use=55, instruction=68, design=50),
        cost=ModelCost(0.00, 0.00), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, max_output_tokens=8192),
        release_date="2025-05-01", family="qwen",
    ),
    ModelEntry(
        id=CF_QWQ_32B, alias="cf/qwq", name="QwQ 32B (CF)",
        hint="Reasoning", provider="cloudflare",
        scores=ModelScores(coding=62, reasoning=75, planning=58, tool_use=52, instruction=66, design=48),
        cost=ModelCost(0.00, 0.00), context_window=131_072, speed_tier="medium",
        capabilities=ModelCapabilities(has_thinking=True, max_output_tokens=8192),
        release_date="2025-03-01", family="qwen",
    ),
    ModelEntry(
        id=CF_MISTRAL_SMALL, alias="cf/mistral", name="Mistral Small 3.1 24B (CF)",
        hint="Fast General", provider="cloudflare",
        scores=ModelScores(coding=58, reasoning=62, planning=50, tool_use=55, instruction=70, design=52),
        cost=ModelCost(0.00, 0.00), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, max_output_tokens=8192),
        release_date="2025-03-01", family="mistral",
    ),
    ModelEntry(
        id=CF_QWEN2_5_CODER, alias="cf/coder", name="Qwen2.5 Coder 32B (CF)",
        hint="Code Gen", provider="cloudflare",
        scores=ModelScores(coding=72, reasoning=60, planning=48, tool_use=50, instruction=62, design=40),
        cost=ModelCost(0.00, 0.00), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(max_output_tokens=8192),
        release_date="2024-11-01", family="qwen",
    ),
    # --- Cloudflare Workers AI Image Generation (5) — free tier ---
    ModelEntry(
        id=CF_FLUX_2_DEV, alias="cf/flux2", name="FLUX.2-dev (CF)",
        hint="Best Image", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=45, design=90),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, can_edit_images=True, max_output_tokens=0),
        release_date="2025-06-01", family="flux",
    ),
    ModelEntry(
        id=CF_FLUX_1_SCHNELL, alias="cf/flux-schnell", name="FLUX.1-schnell (CF)",
        hint="Fast Image", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=35, design=82),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-12-01", family="flux",
    ),
    ModelEntry(
        id=CF_SD_XL_LIGHTNING, alias="cf/sdxl", name="SD XL Lightning (CF)",
        hint="4-Step Fast", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=30, design=75),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-06-01", family="stable-diffusion",
    ),
    ModelEntry(
        id=CF_LEONARDO_PHOENIX, alias="cf/phoenix", name="Leonardo Phoenix (CF)",
        hint="Text Render", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=40, design=85),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2025-01-01", family="leonardo",
    ),
    ModelEntry(
        id=CF_LEONARDO_LUCID, alias="cf/lucid", name="Leonardo Lucid Origin (CF)",
        hint="Design", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=38, design=83),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2025-01-01", family="leonardo",
    ),
]
