"""Insert-only seed entries for UI-selectable models; DB is runtime source."""

from __future__ import annotations

from app.constants.catalog_types import (
    ModelCapabilities,
    ModelCost,
    ModelEntry,
    ModelScores,
)
from app.constants.models import (
    CF_FLUX_1_SCHNELL,
    CF_FLUX_2_DEV,
    CF_GEMMA_4_26B,
    CF_GLM_4_7_FLASH,
    CF_GPT_OSS_20B,
    CF_GPT_OSS_120B,
    CF_GRANITE_4_H_MICRO,
    CF_KIMI_K2_5,
    CF_KIMI_K2_6,
    CF_LEONARDO_LUCID,
    CF_LEONARDO_PHOENIX,
    CF_LLAMA_4_SCOUT,
    CF_MISTRAL_SMALL,
    CF_NEMOTRON_3_120B,
    CF_QWEN2_5_CODER,
    CF_QWEN3_30B,
    CF_QWQ_32B,
    CF_SD_XL_LIGHTNING,
    CLAUDE_HAIKU,
    CLAUDE_OPUS_4_7,
    CLAUDE_SONNET,
    CODEX_GPT_5_1,
    CODEX_GPT_5_1_MINI,
    CODEX_GPT_5_2,
    CODEX_GPT_5_3,
    CODEX_GPT_5_3_SPARK,
    CODEX_GPT_5_4,
    CODEX_GPT_5_4_MINI,
    CODEX_GPT_5_5,
    DEEPSEEK_V4_FLASH,
    DEEPSEEK_V4_PRO,
    GEMINI_2_5_FLASH,
    GEMINI_2_5_FLASH_LITE,
    GEMINI_2_5_PRO,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_FLASH_LITE_PREVIEW,
    GEMINI_3_1_PRO,
    GEMINI_FLASH,
    GEMINI_IMAGE,
    GEMINI_IMAGE_NANO,
    GEMINI_IMAGE_NANO2,
    KIMI_CODE_FOR_CODING,
    LOCAL_GEMMA_4_12B,
    LOCAL_QWEN2_5_CODER_14B,
    LOCAL_QWEN3_30B_A3B,
    LOCAL_QWEN3_CODER_30B_A3B,
    MINIMAX_IMAGE_01,
    MINIMAX_M2_5,
    MINIMAX_M2_5_HIGHSPEED,
    MINIMAX_M2_7,
    MINIMAX_M2_7_HIGHSPEED,
    MINIMAX_M3,
    MOONSHOT_KIMI_K2_5,
    MOONSHOT_KIMI_K2_6,
    NVIDIA_DEEPSEEK_V4_FLASH,
    NVIDIA_FLUX_1_DEV,
    NVIDIA_FLUX_1_KONTEXT,
    NVIDIA_FLUX_1_SCHNELL,
    NVIDIA_KIMI_K2_6,
    NVIDIA_MINIMAX_M2_7,
    NVIDIA_QWEN_3_5,
    NVIDIA_SD_3_5_LARGE,
    OPENAI_GPT_5_4,
    OPENAI_GPT_5_4_MINI,
    OPENAI_GPT_5_4_NANO,
    OPENAI_GPT_5_4_PRO,
    OPENAI_GPT_5_5,
    OR_FREE_GLM,
    OR_FREE_TRINITY,
    OR_KIMI_K2_6,
    XAI_GROK_4_3,
    XAI_GROK_4_20,
    XAI_GROK_4_20_MULTI_AGENT,
    ZHIPU_GLM_4_7,
    ZHIPU_GLM_4_7_FLASH,
    ZHIPU_GLM_4_7_FLASHX,
    ZHIPU_GLM_5,
    ZHIPU_GLM_5_1,
    ZHIPU_GLM_5_TURBO,
)

# Single place to register UI-visible models. Everything else derives from this.
# Static prices are current list prices checked 2026-05-07; DB enrichment may overlay.
MODEL_CATALOG: list[ModelEntry] = [
    # --- Claude ---
    ModelEntry(
        id=CLAUDE_SONNET, alias="sonnet", name="Claude Sonnet 4.6",
        hint="Balanced", provider="claude",
        scores=ModelScores(coding=80, reasoning=87, planning=72, tool_use=78, instruction=84, design=72),
        cost=ModelCost(3.00, 15.00, cache_read_per_million=0.30, cache_write_per_million=3.75),
        context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-01-29", knowledge_cutoff="2025-05-01", family="claude-sonnet",
        availability="external_reference_only; claude_code_tui_only_not_agent_hub_routable",
    ),
    ModelEntry(
        id=CLAUDE_OPUS_4_7, alias="opus", name="Claude Opus 4.7",
        hint="Most capable", provider="claude",
        scores=ModelScores(coding=85, reasoning=93, planning=74, tool_use=78, instruction=86, design=72),
        cost=ModelCost(5.00, 25.00, cache_read_per_million=0.50, cache_write_per_million=6.25),
        context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, max_output_tokens=131_072),
        release_date="2026-04-01", knowledge_cutoff="2026-01-01", family="claude-opus",
        availability="external_reference_only; claude_code_tui_only_not_agent_hub_routable",
    ),
    ModelEntry(
        id=CLAUDE_HAIKU, alias="haiku", name="Claude Haiku 4.5",
        hint="Quick", provider="claude",
        scores=ModelScores(coding=73, reasoning=70, planning=50, tool_use=65, instruction=65, design=60),
        cost=ModelCost(1.00, 5.00, cache_read_per_million=0.10, cache_write_per_million=1.25),
        context_window=200_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2025-10-01", knowledge_cutoff="2025-04-01", family="claude-haiku",
        availability="external_reference_only; claude_code_tui_only_not_agent_hub_routable",
    ),

    # --- Gemini ---
    ModelEntry(
        id=GEMINI_FLASH, alias="flash", name="Gemini 3 Flash Preview",
        hint="Fast", provider="gemini",
        scores=ModelScores(coding=78, reasoning=90, planning=72, tool_use=75, instruction=83, design=85),
        cost=ModelCost(
            0.50, 3.00,
            cache_read_per_million=0.05,
            service_tiers={"default": 1.0, "batch": 0.5, "flex": 0.5, "priority": 1.8},
        ),
        context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, max_output_tokens=65_536),
        release_date="2025-12-11", knowledge_cutoff="2025-09-01", family="gemini-flash",
        availability="free_tier; quotas_project_specific_ai_studio",
    ),
    ModelEntry(
        id=GEMINI_3_1_FLASH_LITE, alias="3.1-flash-lite", name="Gemini 3.1 Flash-Lite",
        hint="High throughput", provider="gemini",
        scores=ModelScores(coding=56, reasoning=64, planning=46, tool_use=49, instruction=86, design=58),
        cost=ModelCost(
            0.25, 1.50,
            cache_read_per_million=0.025,
            service_tiers={"default": 1.0, "batch": 0.5, "flex": 0.5, "priority": 1.8},
        ),
        context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, max_output_tokens=65_536),
        release_date="2026-05-01", knowledge_cutoff="2025-01-01", family="gemini-flash-lite",
        availability="free_tier; quotas_project_specific_ai_studio",
    ),
    ModelEntry(
        id=GEMINI_3_1_FLASH_LITE_PREVIEW, alias="3.1-flash-lite-preview", name="Gemini 3.1 Flash-Lite Preview",
        hint="Agentic cheap", provider="gemini",
        scores=ModelScores(coding=58, reasoning=66, planning=48, tool_use=51, instruction=86, design=58),
        cost=ModelCost(
            0.25, 1.50,
            cache_read_per_million=0.025,
            service_tiers={"default": 1.0, "batch": 0.5, "flex": 0.5, "priority": 1.8},
        ),
        context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, max_output_tokens=65_536),
        release_date="2026-03-03", knowledge_cutoff="2025-01-01", family="gemini-flash-lite",
        availability="free_tier_preview; quotas_project_specific_ai_studio",
    ),
    ModelEntry(
        id=GEMINI_2_5_FLASH, alias="2.5-flash", name="Gemini 2.5 Flash",
        hint="Price performance", provider="gemini",
        scores=ModelScores(coding=72, reasoning=84, planning=68, tool_use=70, instruction=84, design=78),
        cost=ModelCost(
            0.30, 2.50,
            cache_read_per_million=0.03,
            service_tiers={"default": 1.0, "batch": 0.5, "flex": 0.5, "priority": 1.8},
        ),
        context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, max_output_tokens=65_536),
        release_date="2025-03-20", knowledge_cutoff="2025-01-01", family="gemini-flash",
        availability="free_tier; quotas_project_specific_ai_studio",
    ),
    ModelEntry(
        id=GEMINI_2_5_FLASH_LITE, alias="flash-lite", name="Gemini 2.5 Flash-Lite",
        hint="Cheap", provider="gemini",
        scores=ModelScores(coding=34, reasoning=50, planning=40, tool_use=45, instruction=84, design=55),
        cost=ModelCost(
            0.10, 0.40,
            cache_read_per_million=0.01,
            service_tiers={"default": 1.0, "batch": 0.5, "flex": 0.5, "priority": 1.8},
        ),
        context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, max_output_tokens=65_536),
        release_date="2025-06-01", knowledge_cutoff="2025-01-01", family="gemini-flash-lite",
        availability="free_tier; quotas_project_specific_ai_studio",
    ),
    ModelEntry(
        id=GEMINI_3_1_PRO, alias="3.1-pro", name="Gemini 3.1 Pro Preview",
        hint="Deep reasoning", provider="gemini",
        scores=ModelScores(coding=82, reasoning=96, planning=82, tool_use=82, instruction=88, design=90),
        cost=ModelCost(
            2.00, 12.00,
            cache_read_per_million=0.20,
            service_tiers={"default": 1.0, "batch": 0.5, "flex": 0.5, "priority": 1.8},
        ),
        context_window=1_000_000, speed_tier="slow",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, max_output_tokens=65_536),
        release_date="2026-02-01", knowledge_cutoff="2025-11-01", family="gemini-pro",
        availability="paid_only; context_over_200k_costs_more",
    ),
    ModelEntry(
        id=GEMINI_2_5_PRO, alias="2.5-pro", name="Gemini 2.5 Pro",
        hint="Deep reasoning", provider="gemini",
        scores=ModelScores(coding=80, reasoning=92, planning=78, tool_use=80, instruction=86, design=82),
        cost=ModelCost(
            1.25, 10.00,
            cache_read_per_million=0.125,
            service_tiers={"default": 1.0, "batch": 0.5, "flex": 0.5, "priority": 1.8},
        ),
        context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, max_output_tokens=65_536),
        release_date="2025-03-20", knowledge_cutoff="2025-01-01", family="gemini-pro",
        availability="free_tier; context_over_200k_costs_more; quotas_project_specific_ai_studio",
    ),

    # --- Gemini image ---
    ModelEntry(
        id=GEMINI_IMAGE, alias="pro-image", name="Gemini 3 Pro Image",
        hint="Image gen", provider="gemini",
        scores=ModelScores(coding=20, reasoning=40, planning=30, tool_use=25, instruction=60, design=92),
        cost=ModelCost(0.90, 5.40), context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, has_vision=True, can_edit_images=True, max_output_tokens=8_192),
        release_date="2025-12-11", family="gemini-image",
    ),
    ModelEntry(
        id=GEMINI_IMAGE_NANO, alias="nano-banana", name="Nano Banana",
        hint="Fast image", provider="gemini",
        scores=ModelScores(coding=15, reasoning=30, planning=20, tool_use=20, instruction=50, design=80),
        cost=ModelCost(0.50, 3.00), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, has_vision=True, can_edit_images=True, max_output_tokens=8_192),
        release_date="2025-06-01", family="gemini-image",
    ),
    ModelEntry(
        id=GEMINI_IMAGE_NANO2, alias="nano-banana-2", name="Nano Banana 2",
        hint="Fastest image", provider="gemini",
        scores=ModelScores(coding=15, reasoning=35, planning=22, tool_use=22, instruction=55, design=85),
        cost=ModelCost(0.50, 3.00), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, has_vision=True, can_edit_images=True, max_output_tokens=8_192),
        release_date="2026-02-01", family="gemini-image",
    ),

    # --- OpenAI direct ---
    ModelEntry(
        id=OPENAI_GPT_5_5, alias="gpt5.5", name="GPT-5.5",
        hint="Flagship", provider="openai",
        scores=ModelScores(coding=98, reasoning=99, planning=90, tool_use=91, instruction=94, design=82),
        cost=ModelCost(5.00, 30.00, cache_read_per_million=0.50, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=1_050_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, supports_verbosity=True, supports_xhigh=True, max_output_tokens=32_768),
        release_date="2026-04-23", knowledge_cutoff="2026-01-01", family="gpt",
    ),
    ModelEntry(
        id=OPENAI_GPT_5_4, alias="gpt5.4", name="GPT-5.4",
        hint="Frontier", provider="openai",
        scores=ModelScores(coding=95, reasoning=97, planning=85, tool_use=88, instruction=92, design=78),
        cost=ModelCost(2.50, 15.00, cache_read_per_million=0.25, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=1_050_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_audio=True, supports_tool_execution=True, supports_verbosity=True, supports_xhigh=True, max_output_tokens=32_768),
        release_date="2026-03-05", knowledge_cutoff="2025-08-31", family="gpt",
    ),
    ModelEntry(
        id=OPENAI_GPT_5_4_MINI, alias="gpt5.4-mini", name="GPT-5.4 mini",
        hint="Subagents", provider="openai",
        scores=ModelScores(coding=82, reasoning=86, planning=70, tool_use=78, instruction=86, design=70),
        cost=ModelCost(0.75, 4.50, cache_read_per_million=0.075, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, supports_verbosity=True, max_output_tokens=32_768),
        release_date="2026-03-17", knowledge_cutoff="2025-08-31", family="gpt-mini",
    ),
    ModelEntry(
        id=OPENAI_GPT_5_4_NANO, alias="gpt5.4-nano", name="GPT-5.4 nano",
        hint="Extraction", provider="openai",
        scores=ModelScores(coding=58, reasoning=66, planning=46, tool_use=55, instruction=78, design=55),
        cost=ModelCost(0.20, 1.25, cache_read_per_million=0.02, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-03-17", knowledge_cutoff="2025-08-31", family="gpt-nano",
    ),
    ModelEntry(
        id=OPENAI_GPT_5_4_PRO, alias="gpt5.4-pro", name="GPT-5.4 pro",
        hint="Max reasoning", provider="openai",
        scores=ModelScores(coding=96, reasoning=99, planning=90, tool_use=93, instruction=94, design=80),
        cost=ModelCost(30.00, 180.00, service_tiers={"flex": 0.5, "default": 1.0, "priority": 2.0}),
        context_window=1_050_000, speed_tier="slow",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, supports_xhigh=True, max_output_tokens=128_000),
        release_date="2026-03-05", knowledge_cutoff="2025-08-31", family="gpt-pro",
    ),

    # --- Codex OAuth/subscription ---
    ModelEntry(
        id=CODEX_GPT_5_5, alias="codex-5.5", name="GPT-5.5 (Codex)",
        hint="Codex frontier", provider="codex",
        scores=ModelScores(coding=98, reasoning=99, planning=90, tool_use=91, instruction=94, design=82),
        cost=ModelCost(0.00, 0.00), context_window=1_050_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, supports_verbosity=True, supports_xhigh=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-04-23", knowledge_cutoff="2026-01-01", family="gpt",
        availability="codex_oauth_subscription",
    ),
    ModelEntry(
        id=CODEX_GPT_5_4, alias="codex-5.4", name="GPT-5.4 (Codex)",
        hint="Codex frontier", provider="codex",
        scores=ModelScores(coding=95, reasoning=97, planning=85, tool_use=88, instruction=92, design=78),
        cost=ModelCost(0.00, 0.00), context_window=1_050_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, supports_verbosity=True, supports_xhigh=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-03-05", knowledge_cutoff="2025-08-31", family="gpt",
        availability="codex_oauth_subscription",
    ),
    ModelEntry(
        id=CODEX_GPT_5_4_MINI, alias="codex-mini", name="GPT-5.4 mini (Codex)",
        hint="Codex cheap", provider="codex",
        scores=ModelScores(coding=82, reasoning=86, planning=70, tool_use=78, instruction=86, design=70),
        cost=ModelCost(0.00, 0.00), context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, supports_verbosity=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-03-17", knowledge_cutoff="2025-08-31", family="gpt-mini",
        availability="codex_oauth_subscription",
    ),
    ModelEntry(
        id=CODEX_GPT_5_2, alias="codex-5.2", name="GPT-5.2 Codex",
        hint="Legacy coding", provider="codex",
        scores=ModelScores(coding=91, reasoning=93, planning=78, tool_use=78, instruction=88, design=70),
        cost=ModelCost(0.00, 0.00), context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, supports_verbosity=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-01-06", knowledge_cutoff="2025-10-01", family="gpt-codex",
        availability="legacy_compat",
    ),
    ModelEntry(
        id=CODEX_GPT_5_1, alias="codex-5.1", name="GPT-5.1 Codex",
        hint="Legacy coding", provider="codex",
        scores=ModelScores(coding=86, reasoning=88, planning=72, tool_use=72, instruction=84, design=66),
        cost=ModelCost(0.00, 0.00), context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, supports_verbosity=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2025-11-20", knowledge_cutoff="2025-08-31", family="gpt-codex",
        availability="legacy_compat",
    ),
    ModelEntry(
        id=CODEX_GPT_5_1_MINI, alias="codex-5.1-mini", name="GPT-5.1 Codex mini",
        hint="Legacy cheap", provider="codex",
        scores=ModelScores(coding=70, reasoning=72, planning=58, tool_use=0, instruction=72, design=56),
        cost=ModelCost(0.00, 0.00), context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_verbosity=True, supports_session_cache=True, max_output_tokens=16_384),
        release_date="2025-11-20", knowledge_cutoff="2025-08-31", family="gpt-mini",
        availability="legacy_compat",
    ),
    ModelEntry(
        id=CODEX_GPT_5_3, alias="codex-5.3", name="GPT-5.3 Codex",
        hint="Legacy coding", provider="codex",
        scores=ModelScores(coding=93, reasoning=95, planning=80, tool_use=80, instruction=90, design=72),
        cost=ModelCost(0.00, 0.00), context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, supports_verbosity=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-02-05", knowledge_cutoff="2025-10-01", family="gpt-codex",
        availability="legacy_compat",
    ),
    ModelEntry(
        id=CODEX_GPT_5_3_SPARK, alias="codex-spark", name="GPT-5.3 Codex Spark",
        hint="Fast coding", provider="codex",
        scores=ModelScores(coding=88, reasoning=88, planning=72, tool_use=72, instruction=85, design=68),
        cost=ModelCost(0.00, 0.00), context_window=400_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, supports_verbosity=True, supports_session_cache=True, max_output_tokens=16_384),
        release_date="2026-02-12", knowledge_cutoff="2025-10-01", family="gpt-codex",
        availability="legacy_compat",
    ),

    # --- xAI direct ---
    ModelEntry(
        id=XAI_GROK_4_3, alias="grok", name="Grok 4.3",
        hint="xAI current", provider="xai",
        scores=ModelScores(coding=78, reasoning=88, planning=82, tool_use=84, instruction=84, design=72),
        cost=ModelCost(1.25, 2.50), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-04-30", family="grok",
    ),
    ModelEntry(
        id=XAI_GROK_4_20, alias="grok-4.20", name="Grok 4.20 Reasoning",
        hint="2M context", provider="xai",
        scores=ModelScores(coding=75, reasoning=88, planning=86, tool_use=84, instruction=84, design=72),
        cost=ModelCost(1.25, 2.50), context_window=2_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-03-09", family="grok-4.20",
    ),
    ModelEntry(
        id=XAI_GROK_4_20_MULTI_AGENT, alias="grok-research", name="Grok 4.20 Multi-Agent",
        hint="Deep research", provider="xai",
        scores=ModelScores(coding=72, reasoning=91, planning=94, tool_use=70, instruction=86, design=68),
        cost=ModelCost(1.25, 2.50), context_window=2_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_thinking=True, supports_session_cache=True, max_output_tokens=32_768),
        release_date="2026-03-09", family="grok-4.20",
    ),

    # --- DeepSeek direct ---
    ModelEntry(
        id=DEEPSEEK_V4_FLASH, alias="deepseek", name="DeepSeek V4 Flash",
        hint="Best cheap", provider="deepseek",
        scores=ModelScores(coding=78, reasoning=86, planning=78, tool_use=82, instruction=84, design=62),
        cost=ModelCost(0.14, 0.28, cache_read_per_million=0.0028),
        context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=384_000),
        release_date="2026-04-24", family="deepseek-v4",
    ),
    ModelEntry(
        id=DEEPSEEK_V4_PRO, alias="deepseek-pro", name="DeepSeek V4 Pro",
        hint="Cheap reasoning", provider="deepseek",
        scores=ModelScores(coding=84, reasoning=92, planning=84, tool_use=86, instruction=87, design=65),
        cost=ModelCost(0.435, 0.87, cache_read_per_million=0.003625),
        context_window=1_000_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=384_000),
        release_date="2026-04-24", family="deepseek-v4",
        availability="75pct_discount_until_2026-05-31_standard_1.74_3.48",
    ),

    # --- Z.AI / GLM direct ---
    ModelEntry(
        id=ZHIPU_GLM_5_1, alias="glm5.1", name="GLM-5.1",
        hint="GLM latest", provider="zhipu",
        scores=ModelScores(coding=82, reasoning=94, planning=74, tool_use=79, instruction=87, design=70),
        cost=ModelCost(1.40, 4.40, cache_read_per_million=0.26),
        context_window=200_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-04-01", family="glm",
    ),
    ModelEntry(
        id=ZHIPU_GLM_5, alias="glm5", name="GLM-5",
        hint="GLM reasoning", provider="zhipu",
        scores=ModelScores(coding=78, reasoning=92, planning=70, tool_use=75, instruction=85, design=68),
        cost=ModelCost(1.00, 3.20, cache_read_per_million=0.20),
        context_window=200_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2025-10-01", family="glm",
    ),
    ModelEntry(
        id=ZHIPU_GLM_5_TURBO, alias="glm5-turbo", name="GLM-5-Turbo",
        hint="GLM turbo", provider="zhipu",
        scores=ModelScores(coding=76, reasoning=88, planning=68, tool_use=74, instruction=84, design=66),
        cost=ModelCost(1.20, 4.00, cache_read_per_million=0.24),
        context_window=200_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-03-01", family="glm",
    ),
    ModelEntry(
        id=ZHIPU_GLM_4_7, alias="glm4.7", name="GLM-4.7",
        hint="Balanced GLM", provider="zhipu",
        scores=ModelScores(coding=74, reasoning=90, planning=67, tool_use=85, instruction=82, design=70),
        cost=ModelCost(0.60, 2.20, cache_read_per_million=0.11),
        context_window=200_000, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-01-15", family="glm",
    ),
    ModelEntry(
        id=ZHIPU_GLM_4_7_FLASHX, alias="glm-flashx", name="GLM-4.7-FlashX",
        hint="Cheap GLM", provider="zhipu",
        scores=ModelScores(coding=66, reasoning=75, planning=58, tool_use=70, instruction=78, design=58),
        cost=ModelCost(0.07, 0.40, cache_read_per_million=0.01),
        context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-01-15", family="glm",
    ),
    ModelEntry(
        id=ZHIPU_GLM_4_7_FLASH, alias="glm-free", name="GLM-4.7-Flash",
        hint="Free", provider="zhipu",
        scores=ModelScores(coding=58, reasoning=66, planning=52, tool_use=62, instruction=72, design=52),
        cost=ModelCost(0.00, 0.00),
        context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-01-15", family="glm",
        availability="free_tier",
    ),

    # --- MiniMax direct ---
    ModelEntry(
        id=MINIMAX_M3, alias="minimax-m3", name="MiniMax M3",
        hint="Agentic reasoning + long context", provider="minimax",
        scores=ModelScores(coding=86, reasoning=90, planning=84, tool_use=86, instruction=88, design=66),
        cost=ModelCost(0.30, 1.20, cache_read_per_million=0.06, cache_write_per_million=0.375),
        context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=131_072),
        release_date="2026-06-01", family="minimax",
    ),
    ModelEntry(
        id=MINIMAX_M2_7, alias="minimax", name="MiniMax M2.7",
        hint="Agent coding", provider="minimax",
        scores=ModelScores(coding=84, reasoning=88, planning=80, tool_use=82, instruction=86, design=64),
        cost=ModelCost(0.30, 1.20, cache_read_per_million=0.06, cache_write_per_million=0.375),
        context_window=204_800, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=131_072),
        release_date="2026-03-27", knowledge_cutoff="2025-11-01", family="minimax",
    ),
    ModelEntry(
        id=MINIMAX_M2_7_HIGHSPEED, alias="minimax-fast", name="MiniMax M2.7 highspeed",
        hint="Fast agent", provider="minimax",
        scores=ModelScores(coding=84, reasoning=88, planning=80, tool_use=82, instruction=86, design=64),
        cost=ModelCost(0.60, 2.40, cache_read_per_million=0.06, cache_write_per_million=0.375),
        context_window=204_800, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=131_072),
        release_date="2026-03-27", knowledge_cutoff="2025-11-01", family="minimax",
    ),
    ModelEntry(
        id=MINIMAX_M2_5, alias="minimax-m2.5", name="MiniMax M2.5",
        hint="Cheap coding", provider="minimax",
        scores=ModelScores(coding=80, reasoning=85, planning=76, tool_use=77, instruction=84, design=60),
        cost=ModelCost(0.30, 1.20, cache_read_per_million=0.03, cache_write_per_million=0.375),
        context_window=204_800, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=131_072),
        release_date="2026-02-12", knowledge_cutoff="2025-09-01", family="minimax",
    ),
    ModelEntry(
        id=MINIMAX_M2_5_HIGHSPEED, alias="minimax-m2.5-fast", name="MiniMax M2.5 highspeed",
        hint="Cheap fast", provider="minimax",
        scores=ModelScores(coding=80, reasoning=85, planning=76, tool_use=77, instruction=84, design=60),
        cost=ModelCost(0.60, 2.40, cache_read_per_million=0.03, cache_write_per_million=0.375),
        context_window=204_800, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=131_072),
        release_date="2026-02-12", knowledge_cutoff="2025-09-01", family="minimax",
    ),

    # --- Kimi Code subscription ---
    ModelEntry(
        id=KIMI_CODE_FOR_CODING, alias="kimi-code", name="Kimi Code",
        hint="Subscription coding", provider="kimi-code",
        scores=ModelScores(coding=90, reasoning=93, planning=88, tool_use=90, instruction=88, design=82),
        cost=ModelCost(0.00, 0.00),
        context_window=262_144, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-04-20", family="kimi",
        availability="subscription",
    ),

    # --- Moonshot/Kimi direct ---
    ModelEntry(
        id=MOONSHOT_KIMI_K2_6, alias="kimi", name="Kimi K2.6",
        hint="Agent coding", provider="moonshot",
        scores=ModelScores(coding=90, reasoning=93, planning=88, tool_use=90, instruction=88, design=85),
        cost=ModelCost(0.95, 4.00, cache_read_per_million=0.16),
        context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-04-20", family="kimi",
    ),
    ModelEntry(
        id=MOONSHOT_KIMI_K2_5, alias="kimi-cheap", name="Kimi K2.5",
        hint="Cheap Kimi", provider="moonshot",
        scores=ModelScores(coding=82, reasoning=90, planning=80, tool_use=84, instruction=84, design=82),
        cost=ModelCost(0.60, 3.00, cache_read_per_million=0.10),
        context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-01-01", family="kimi",
    ),

    # --- OpenRouter ---
    ModelEntry(
        id=OR_KIMI_K2_6, alias="or/kimi", name="Kimi K2.6 (OpenRouter)",
        hint="Best Kimi price", provider="openrouter",
        scores=ModelScores(coding=90, reasoning=93, planning=88, tool_use=90, instruction=88, design=85),
        cost=ModelCost(0.75, 3.50), context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-04-20", family="kimi",
    ),
    ModelEntry(
        id=OR_FREE_TRINITY, alias="or/free-trinity", name="Trinity Large (Free)",
        hint="Free", provider="openrouter",
        scores=ModelScores(coding=55, reasoning=60, planning=45, tool_use=50, instruction=65, design=45),
        cost=ModelCost(0.00, 0.00), context_window=128_000, speed_tier="fast",
        family="trinity", availability="free_openrouter",
    ),
    ModelEntry(
        id=OR_FREE_GLM, alias="or/free-glm", name="GLM-4.5 Air (Free)",
        hint="Free GLM", provider="openrouter",
        scores=ModelScores(coding=60, reasoning=65, planning=50, tool_use=55, instruction=70, design=50),
        cost=ModelCost(0.00, 0.00), context_window=128_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True),
        family="glm", availability="free_openrouter",
    ),

    # --- Local OpenAI-compatible ---
    ModelEntry(
        id=LOCAL_GEMMA_4_12B, alias="local/gemma", name="Gemma 4 12B QAT (Local)",
        hint="Local multimodal", provider="local",
        scores=ModelScores(coding=52, reasoning=64, planning=56, tool_use=60, instruction=74, design=55),
        cost=ModelCost(0.00, 0.00), context_window=32_768, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2026-06-03", family="gemma",
        availability="requires_local_openai_endpoint; qat_q4_0_~8gb_vram_100pct_gpu",
    ),
    ModelEntry(
        id=LOCAL_QWEN3_CODER_30B_A3B, alias="local/qwen-coder", name="Qwen3-Coder 30B-A3B (Local)",
        hint="Local code", provider="local",
        scores=ModelScores(coding=70, reasoning=62, planning=55, tool_use=58, instruction=72, design=55),
        cost=ModelCost(0.00, 0.00), context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2025-07-01", family="qwen",
        availability="requires_local_openai_endpoint; 16gb_vram_use_q4_reduced_context",
    ),
    ModelEntry(
        id=LOCAL_QWEN3_30B_A3B, alias="local/qwen3", name="Qwen3 30B-A3B (Local)",
        hint="Local utility", provider="local",
        scores=ModelScores(coding=58, reasoning=68, planning=54, tool_use=54, instruction=72, design=50),
        cost=ModelCost(0.00, 0.00), context_window=262_144, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2025-04-01", family="qwen",
        availability="requires_local_openai_endpoint; 16gb_vram_use_q4_reduced_context",
    ),
    ModelEntry(
        id=LOCAL_QWEN2_5_CODER_14B, alias="local/coder-14b", name="Qwen2.5-Coder 14B (Local)",
        hint="Local fast", provider="local",
        scores=ModelScores(coding=62, reasoning=48, planning=42, tool_use=45, instruction=66, design=45),
        cost=ModelCost(0.00, 0.00), context_window=128_000, speed_tier="fast",
        capabilities=ModelCapabilities(supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2024-11-01", family="qwen",
        availability="requires_local_openai_endpoint; stable_16gb_vram",
    ),

    # --- NVIDIA NIM ---
    ModelEntry(
        id=NVIDIA_QWEN_3_5, alias="nv/qwen", name="Qwen 3.5 397B (NVIDIA)",
        hint="Free tier", provider="nvidia",
        scores=ModelScores(coding=82, reasoning=92, planning=78, tool_use=76, instruction=82, design=86),
        cost=ModelCost(0.00, 0.00), context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_pdf=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-02-16", knowledge_cutoff="2025-09-01", family="qwen",
        availability="nvidia_dev_free_tier",
    ),
    ModelEntry(
        id=NVIDIA_DEEPSEEK_V4_FLASH, alias="nv/deepseek", name="DeepSeek V4 Flash (NVIDIA)",
        hint="Free cheap", provider="nvidia",
        scores=ModelScores(coding=78, reasoning=86, planning=78, tool_use=82, instruction=84, design=62),
        cost=ModelCost(0.00, 0.00), context_window=1_000_000, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=384_000),
        release_date="2026-04-24", family="deepseek-v4",
        availability="nvidia_dev_free_endpoint",
    ),
    ModelEntry(
        id=NVIDIA_MINIMAX_M2_7, alias="nv/minimax", name="MiniMax M2.7 (NVIDIA)",
        hint="Free coding", provider="nvidia",
        scores=ModelScores(coding=84, reasoning=88, planning=80, tool_use=82, instruction=86, design=64),
        cost=ModelCost(0.00, 0.00), context_window=204_800, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=131_072),
        release_date="2026-03-27", knowledge_cutoff="2025-11-01", family="minimax",
        availability="nvidia_dev_free_endpoint",
    ),
    ModelEntry(
        id=NVIDIA_KIMI_K2_6, alias="nv/kimi", name="Kimi K2.6 (NVIDIA)",
        hint="Free Kimi", provider="nvidia",
        scores=ModelScores(coding=90, reasoning=93, planning=88, tool_use=90, instruction=88, design=85),
        cost=ModelCost(0.00, 0.00), context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-04-20", knowledge_cutoff="2025-11-01", family="kimi",
        availability="nvidia_dev_free_endpoint",
    ),

    # --- NVIDIA image ---
    ModelEntry(
        id=NVIDIA_FLUX_1_DEV, alias="nv/flux-dev", name="FLUX.1-dev (NVIDIA)",
        hint="Image gen", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=40, design=88),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="slow",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-12-01", family="flux",
    ),
    ModelEntry(
        id=NVIDIA_FLUX_1_SCHNELL, alias="nv/flux-schnell", name="FLUX.1-schnell (NVIDIA)",
        hint="Fast image", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=35, design=82),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-12-01", family="flux",
    ),
    ModelEntry(
        id=NVIDIA_SD_3_5_LARGE, alias="nv/sd3.5", name="Stable Diffusion 3.5 Large (NVIDIA)",
        hint="Image gen", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=38, design=85),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-10-01", family="stable-diffusion",
    ),
    ModelEntry(
        id=NVIDIA_FLUX_1_KONTEXT, alias="nv/flux-kontext", name="FLUX.1-Kontext (NVIDIA)",
        hint="Image edit", provider="nvidia",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=50, design=90),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, can_edit_images=True, max_output_tokens=0),
        release_date="2025-06-01", family="flux",
    ),

    # --- MiniMax image ---
    ModelEntry(
        id=MINIMAX_IMAGE_01, alias="mm/image-01", name="MiniMax Image-01",
        hint="Image gen", provider="minimax",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=35, design=80),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.0035), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2025-02-15", family="minimax-image",
    ),

    # --- Cloudflare Workers AI LLM ---
    ModelEntry(
        id=CF_KIMI_K2_6, alias="cf/kimi", name="Kimi K2.6 (Cloudflare)",
        hint="Agent coding", provider="cloudflare",
        scores=ModelScores(coding=90, reasoning=93, planning=88, tool_use=90, instruction=88, design=85),
        cost=ModelCost(0.95, 4.00, cache_read_per_million=0.16), context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-04-20", family="kimi",
    ),
    ModelEntry(
        id=CF_KIMI_K2_5, alias="cf/kimi-cheap", name="Kimi K2.5 (Cloudflare)",
        hint="Cheap Kimi", provider="cloudflare",
        scores=ModelScores(coding=82, reasoning=90, planning=80, tool_use=84, instruction=84, design=82),
        cost=ModelCost(0.60, 3.00, cache_read_per_million=0.10), context_window=262_144, speed_tier="medium",
        capabilities=ModelCapabilities(has_vision=True, has_thinking=True, supports_tool_execution=True, max_output_tokens=32_768),
        release_date="2026-01-01", family="kimi",
    ),
    ModelEntry(
        id=CF_GLM_4_7_FLASH, alias="cf/glm", name="GLM-4.7-Flash (Cloudflare)",
        hint="Very cheap", provider="cloudflare",
        scores=ModelScores(coding=58, reasoning=66, planning=52, tool_use=62, instruction=72, design=52),
        cost=ModelCost(0.06, 0.40), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-01-15", family="glm",
    ),
    ModelEntry(
        id=CF_QWEN3_30B, alias="cf/qwen3", name="Qwen3 30B-A3B (Cloudflare)",
        hint="Cheap thinking", provider="cloudflare",
        scores=ModelScores(coding=60, reasoning=70, planning=55, tool_use=55, instruction=68, design=50),
        cost=ModelCost(0.051, 0.335), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2025-05-01", family="qwen",
    ),
    ModelEntry(
        id=CF_GPT_OSS_120B, alias="cf/gpt-oss", name="GPT-OSS 120B (Cloudflare)",
        hint="OSS general", provider="cloudflare",
        scores=ModelScores(coding=68, reasoning=74, planning=60, tool_use=62, instruction=74, design=55),
        cost=ModelCost(0.35, 0.75), context_window=131_072, speed_tier="medium",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-04-01", family="gpt-oss",
    ),
    ModelEntry(
        id=CF_GPT_OSS_20B, alias="cf/gpt-oss-20b", name="GPT-OSS 20B (Cloudflare)",
        hint="OSS cheap", provider="cloudflare",
        scores=ModelScores(coding=58, reasoning=62, planning=50, tool_use=55, instruction=70, design=50),
        cost=ModelCost(0.20, 0.30), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2026-04-01", family="gpt-oss",
    ),
    ModelEntry(
        id=CF_LLAMA_4_SCOUT, alias="cf/llama", name="Llama 4 Scout 17B (Cloudflare)",
        hint="Multimodal", provider="cloudflare",
        scores=ModelScores(coding=55, reasoning=60, planning=50, tool_use=50, instruction=65, design=55),
        cost=ModelCost(0.270, 0.850), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2025-04-01", family="llama",
    ),
    ModelEntry(
        id=CF_QWQ_32B, alias="cf/qwq", name="QwQ 32B (Cloudflare)",
        hint="Reasoning", provider="cloudflare",
        scores=ModelScores(coding=62, reasoning=75, planning=58, tool_use=52, instruction=66, design=48),
        cost=ModelCost(0.660, 1.000), context_window=131_072, speed_tier="medium",
        capabilities=ModelCapabilities(has_thinking=True, max_output_tokens=8_192),
        release_date="2025-03-01", family="qwen",
    ),
    ModelEntry(
        id=CF_MISTRAL_SMALL, alias="cf/mistral", name="Mistral Small 3.1 24B (Cloudflare)",
        hint="Fast general", provider="cloudflare",
        scores=ModelScores(coding=58, reasoning=62, planning=50, tool_use=55, instruction=70, design=52),
        cost=ModelCost(0.351, 0.555), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(has_vision=True, supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2025-03-01", family="mistral",
    ),
    ModelEntry(
        id=CF_QWEN2_5_CODER, alias="cf/coder", name="Qwen2.5 Coder 32B (Cloudflare)",
        hint="Code gen", provider="cloudflare",
        scores=ModelScores(coding=72, reasoning=60, planning=48, tool_use=50, instruction=62, design=40),
        cost=ModelCost(0.660, 1.000), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2024-11-01", family="qwen",
    ),
    ModelEntry(
        id=CF_GEMMA_4_26B, alias="cf/gemma", name="Gemma 4 26B (Cloudflare)",
        hint="Cheap general", provider="cloudflare",
        scores=ModelScores(coding=56, reasoning=62, planning=50, tool_use=50, instruction=70, design=50),
        cost=ModelCost(0.10, 0.30), context_window=131_072, speed_tier="fast",
        capabilities=ModelCapabilities(supports_tool_execution=True, max_output_tokens=8_192),
        release_date="2026-04-01", family="gemma",
    ),
    ModelEntry(
        id=CF_GRANITE_4_H_MICRO, alias="cf/granite", name="Granite 4.0-H Micro (Cloudflare)",
        hint="Tiny cheap", provider="cloudflare",
        scores=ModelScores(coding=45, reasoning=50, planning=40, tool_use=42, instruction=62, design=40),
        cost=ModelCost(0.017, 0.112), context_window=32_768, speed_tier="fast",
        capabilities=ModelCapabilities(supports_tool_execution=True, max_output_tokens=4_096),
        release_date="2026-04-01", family="granite",
    ),
    ModelEntry(
        id=CF_NEMOTRON_3_120B, alias="cf/nemotron", name="Nemotron 3 120B (Cloudflare)",
        hint="Reasoning", provider="cloudflare",
        scores=ModelScores(coding=72, reasoning=84, planning=72, tool_use=70, instruction=80, design=58),
        cost=ModelCost(0.50, 1.50), context_window=131_072, speed_tier="medium",
        capabilities=ModelCapabilities(has_thinking=True, supports_tool_execution=True, max_output_tokens=16_384),
        release_date="2026-03-01", family="nemotron",
    ),

    # --- Cloudflare image ---
    ModelEntry(
        id=CF_FLUX_2_DEV, alias="cf/flux2", name="FLUX.2-dev (Cloudflare)",
        hint="Best image", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=45, design=90),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, can_edit_images=True, max_output_tokens=0),
        release_date="2025-06-01", family="flux",
    ),
    ModelEntry(
        id=CF_FLUX_1_SCHNELL, alias="cf/flux-schnell", name="FLUX.1-schnell (Cloudflare)",
        hint="Fast image", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=35, design=82),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-12-01", family="flux",
    ),
    ModelEntry(
        id=CF_SD_XL_LIGHTNING, alias="cf/sdxl", name="SD XL Lightning (Cloudflare)",
        hint="4-step fast", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=30, design=75),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="fast",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2024-06-01", family="stable-diffusion",
    ),
    ModelEntry(
        id=CF_LEONARDO_PHOENIX, alias="cf/phoenix", name="Leonardo Phoenix (Cloudflare)",
        hint="Text render", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=40, design=85),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2025-01-01", family="leonardo",
    ),
    ModelEntry(
        id=CF_LEONARDO_LUCID, alias="cf/lucid", name="Leonardo Lucid Origin (Cloudflare)",
        hint="Design", provider="cloudflare",
        scores=ModelScores(coding=0, reasoning=0, planning=0, tool_use=0, instruction=38, design=83),
        cost=ModelCost(0.00, 0.00, pricing_unit="per_image", unit_price=0.00), context_window=0, speed_tier="medium",
        capabilities=ModelCapabilities(can_generate_images=True, max_output_tokens=0),
        release_date="2025-01-01", family="leonardo",
    ),
]


# Fallback used only when a model id is not registered in MODEL_CATALOG. Picked
# so under-provisioning (truncated plans) is preferred over silent over-cap
# rejection — current API ceilings for our completion models sit between 16k
# and 128k. Adapters resolve via _MODEL_MAX_OUTPUT_TOKENS first.
_MAX_OUTPUT_TOKENS_FALLBACK = 32_768


_MODEL_MAX_OUTPUT_TOKENS: dict[str, int] = {
    entry.id: entry.capabilities.max_output_tokens
    for entry in MODEL_CATALOG
    if entry.capabilities.max_output_tokens > 0
}


def get_max_output_tokens(model_id: str) -> int:
    """Return the catalog's max_output_tokens for a model id, or the fallback.

    Used by adapters whose upstream API requires an explicit max_tokens (notably
    the Anthropic Messages API). Adapters where the provider treats max_tokens
    as optional should not call this — they should send no cap and let the
    provider use its native default.
    """
    return _MODEL_MAX_OUTPUT_TOKENS.get(model_id, _MAX_OUTPUT_TOKENS_FALLBACK)
