"""add truncation_events table

Revision ID: 27229f433f34
Revises: b9f50737450a
Create Date: 2026-01-09 12:27:21.033914

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27229f433f34"
down_revision: str | Sequence[str] | None = "b9f50737450a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "truncation_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=50), nullable=False),
        sa.Column("max_tokens_requested", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("model_limit", sa.Integer(), nullable=False),
        sa.Column("was_capped", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_truncation_events_created", "truncation_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_truncation_events_model"), "truncation_events", ["model"], unique=False
    )
    op.create_index(
        "ix_truncation_events_model_created",
        "truncation_events",
        ["model", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_truncation_events_project_id"), "truncation_events", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_truncation_events_project_id"), table_name="truncation_events")
    op.drop_index("ix_truncation_events_model_created", table_name="truncation_events")
    op.drop_index(op.f("ix_truncation_events_model"), table_name="truncation_events")
    op.drop_index("ix_truncation_events_created", table_name="truncation_events")
    op.drop_table("truncation_events")
    # ### end Alembic commands ###
