"""extend_api_key_prefix_length

Revision ID: 5d106fee3146
Revises: 548fe3a69c99
Create Date: 2026-01-06 21:06:12.699893

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d106fee3146"
down_revision: str | Sequence[str] | None = "548fe3a69c99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_keys",
        "key_prefix",
        existing_type=sa.VARCHAR(length=12),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_keys",
        "key_prefix",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=12),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
