"""remove_max_tokens_from_agents

Revision ID: 6b46071ec3b1
Revises: i8j9k0l1m2n3
Create Date: 2026-01-24 17:07:09.020018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b46071ec3b1'
down_revision: Union[str, Sequence[str], None] = 'i8j9k0l1m2n3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'max_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
