"""mark_legacy_sessions

Revision ID: 78ebdaac1078
Revises: 86bacf829f75
Create Date: 2026-01-23 10:29:51.423279

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78ebdaac1078"
down_revision: str | Sequence[str] | None = "86bacf829f75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default False first (to allow NOT NULL)
    op.add_column(
        "sessions", sa.Column("is_legacy", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_index(op.f("ix_sessions_is_legacy"), "sessions", ["is_legacy"], unique=False)

    # Mark all existing sessions with NULL client_id as legacy
    op.execute("UPDATE sessions SET is_legacy = true WHERE client_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_is_legacy"), table_name="sessions")
    op.drop_column("sessions", "is_legacy")
    # ### end Alembic commands ###
