"""add_access_control_tables

Revision ID: 86bacf829f75
Revises: g6h7i8j9k0l1
Create Date: 2026-01-22 18:30:00.398494

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86bacf829f75"
down_revision: str | Sequence[str] | None = "g6h7i8j9k0l1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "client_type",
            sa.Enum("internal", "external", "service", name="client_type_enum"),
            nullable=False,
        ),
        sa.Column("secret_hash", sa.String(length=128), nullable=False),
        sa.Column("secret_prefix", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "blocked", name="client_status_enum"),
            nullable=False,
        ),
        sa.Column("rate_limit_rpm", sa.Integer(), nullable=False),
        sa.Column("rate_limit_tpm", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_by", sa.String(length=100), nullable=True),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_clients_display_name", "clients", ["display_name"], unique=False)
    op.create_index("ix_clients_status", "clients", ["status"], unique=False)
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("request_source", sa.String(length=100), nullable=True),
        sa.Column("endpoint", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column(
            "rejection_reason",
            sa.Enum(
                "missing_required_headers",
                "authentication_failed",
                "client_suspended",
                "client_blocked",
                "rate_limited",
                name="rejection_reason_enum",
            ),
            nullable=True,
        ),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_request_logs_client_created", "request_logs", ["client_id", "created_at"], unique=False
    )
    op.create_index("ix_request_logs_client_id", "request_logs", ["client_id"], unique=False)
    op.create_index("ix_request_logs_created_at", "request_logs", ["created_at"], unique=False)
    op.create_index("ix_request_logs_status_code", "request_logs", ["status_code"], unique=False)
    op.add_column("sessions", sa.Column("client_id", sa.String(length=36), nullable=True))
    op.add_column("sessions", sa.Column("request_source", sa.String(length=100), nullable=True))
    op.create_foreign_key(None, "sessions", "clients", ["client_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_column("sessions", "request_source")
    op.drop_column("sessions", "client_id")
    op.drop_index("ix_request_logs_status_code", table_name="request_logs")
    op.drop_index("ix_request_logs_created_at", table_name="request_logs")
    op.drop_index("ix_request_logs_client_id", table_name="request_logs")
    op.drop_index("ix_request_logs_client_created", table_name="request_logs")
    op.drop_table("request_logs")
    op.drop_index("ix_clients_status", table_name="clients")
    op.drop_index("ix_clients_display_name", table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
