"""add_agent_id_to_messages

Revision ID: 98f371912aa2
Revises: ed13ea976211
Create Date: 2026-01-12 16:50:18.662224

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98f371912aa2"
down_revision: str | Sequence[str] | None = "ed13ea976211"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("agent_id", sa.String(length=100), nullable=True))
    op.add_column("messages", sa.Column("agent_name", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_messages_agent_id"), "messages", ["agent_id"], unique=False)
    op.create_index(
        "ix_messages_session_agent", "messages", ["session_id", "agent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_session_agent", table_name="messages")
    op.drop_index(op.f("ix_messages_agent_id"), table_name="messages")
    op.drop_column("messages", "agent_name")
    op.drop_column("messages", "agent_id")
    # ### end Alembic commands ###
