"""add_webhook_subscriptions_table

Revision ID: b9f50737450a
Revises: 5d106fee3146
Create Date: 2026-01-08 21:09:57.755670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f50737450a'
down_revision: Union[str, Sequence[str], None] = '5d106fee3146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('verbosity', sa.Enum('concise', 'normal', 'detailed', name='verbosity_level'), nullable=False),
    sa.Column('tone', sa.Enum('professional', 'friendly', 'technical', name='tone_type'), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_subscriptions_project', 'webhook_subscriptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_project_id'), 'webhook_subscriptions', ['project_id'], unique=False)
    op.create_table('message_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('feedback_type', sa.Enum('positive', 'negative', name='feedback_type'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_feedback_message', 'message_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=False)
    op.create_index('ix_message_feedback_session', 'message_feedback', ['session_id'], unique=False)
    op.create_index('ix_message_feedback_type', 'message_feedback', ['feedback_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_feedback_type', table_name='message_feedback')
    op.drop_index('ix_message_feedback_session', table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_index('ix_message_feedback_message', table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_index(op.f('ix_webhook_subscriptions_project_id'), table_name='webhook_subscriptions')
    op.drop_index('ix_webhook_subscriptions_project', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
