"""Add llm_models table

Revision ID: e281dbbb5cf4
Revises: 8939a1bd7848
Create Date: 2026-01-17 16:51:37.560645

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e281dbbb5cf4"
down_revision: str | Sequence[str] | None = "8939a1bd7848"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_models",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("family", sa.String(length=50), nullable=True),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=True),
        sa.Column("input_price_per_m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("output_price_per_m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=True),
        sa.Column("is_deprecated", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_llm_models_provider", "llm_models", ["provider"], unique=False)
    op.create_index(
        "ix_llm_models_provider_active", "llm_models", ["provider", "is_active"], unique=False
    )

    # Seed data for current models
    llm_models = sa.table(
        "llm_models",
        sa.column("id", sa.String),
        sa.column("display_name", sa.String),
        sa.column("provider", sa.String),
        sa.column("family", sa.String),
        sa.column("context_window", sa.Integer),
        sa.column("max_output_tokens", sa.Integer),
        sa.column("input_price_per_m", sa.Numeric),
        sa.column("output_price_per_m", sa.Numeric),
        sa.column("capabilities", sa.JSON),
        sa.column("is_deprecated", sa.Boolean),
        sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )

    now = datetime.now(UTC)
    op.bulk_insert(
        llm_models,
        [
            # Claude 4.5 models (Anthropic)
            {
                "id": "claude-sonnet-4-5",
                "display_name": "Claude Sonnet 4.5",
                "provider": "anthropic",
                "family": "claude-4",
                "context_window": 200000,
                "max_output_tokens": 64000,
                "input_price_per_m": 3.0,
                "output_price_per_m": 15.0,
                "capabilities": {"vision": True, "function_calling": True},
                "is_deprecated": False,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "claude-opus-4-5",
                "display_name": "Claude Opus 4.5",
                "provider": "anthropic",
                "family": "claude-4",
                "context_window": 200000,
                "max_output_tokens": 64000,
                "input_price_per_m": 15.0,
                "output_price_per_m": 75.0,
                "capabilities": {"vision": True, "function_calling": True},
                "is_deprecated": False,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "claude-haiku-4-5",
                "display_name": "Claude Haiku 4.5",
                "provider": "anthropic",
                "family": "claude-4",
                "context_window": 200000,
                "max_output_tokens": 64000,
                "input_price_per_m": 0.8,
                "output_price_per_m": 4.0,
                "capabilities": {"vision": True, "function_calling": True},
                "is_deprecated": False,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            # Gemini 3 models (Google)
            {
                "id": "gemini-3-flash-preview",
                "display_name": "Gemini 3 Flash",
                "provider": "google",
                "family": "gemini-3",
                "context_window": 1000000,
                "max_output_tokens": 65536,
                "input_price_per_m": 0.075,
                "output_price_per_m": 0.30,
                "capabilities": {"vision": True, "function_calling": True},
                "is_deprecated": False,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "gemini-3-pro-preview",
                "display_name": "Gemini 3 Pro",
                "provider": "google",
                "family": "gemini-3",
                "context_window": 1000000,
                "max_output_tokens": 65536,
                "input_price_per_m": 1.25,
                "output_price_per_m": 5.0,
                "capabilities": {"vision": True, "function_calling": True},
                "is_deprecated": False,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "gemini-3-pro-image-preview",
                "display_name": "Gemini 3 Pro Image",
                "provider": "google",
                "family": "gemini-3",
                "context_window": 1000000,
                "max_output_tokens": 65536,
                "input_price_per_m": 1.25,
                "output_price_per_m": 5.0,
                "capabilities": {"vision": True, "image_gen": True},
                "is_deprecated": False,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_models_provider_active", table_name="llm_models")
    op.drop_index("ix_llm_models_provider", table_name="llm_models")
    op.drop_table("llm_models")
    # ### end Alembic commands ###
