"""add multi-model tracking columns

Revision ID: eb4ecc28ced9
Revises: 6b46071ec3b1
Create Date: 2026-01-24 21:37:47.203034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4ecc28ced9'
down_revision: Union[str, Sequence[str], None] = '6b46071ec3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model_used', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('models_used', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('providers_used', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'providers_used')
    op.drop_column('sessions', 'models_used')
    op.drop_column('messages', 'model_used')
    # ### end Alembic commands ###
